/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BlockEditorPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");
var import_view3 = require("@codemirror/view");

// src/state.ts
var import_state = require("@codemirror/state");
var toggleBlockMode = import_state.StateEffect.define();
var toggleBlockSelection = import_state.StateEffect.define();
var setBlockSelection = import_state.StateEffect.define();
var clearBlockSelection = import_state.StateEffect.define();
var blockSelectionState = import_state.StateField.define({
  create() {
    return { active: false, selectedBlocks: /* @__PURE__ */ new Set() };
  },
  update(value, tr) {
    let result = value;
    for (const effect of tr.effects) {
      if (effect.is(toggleBlockMode)) {
        result = {
          active: effect.value,
          selectedBlocks: /* @__PURE__ */ new Set()
        };
      } else if (effect.is(toggleBlockSelection)) {
        const newSet = new Set(result.selectedBlocks);
        if (newSet.has(effect.value)) {
          newSet.delete(effect.value);
        } else {
          newSet.add(effect.value);
        }
        result = { active: result.active, selectedBlocks: newSet };
      } else if (effect.is(setBlockSelection)) {
        result = { active: result.active, selectedBlocks: effect.value };
      } else if (effect.is(clearBlockSelection)) {
        result = { active: result.active, selectedBlocks: /* @__PURE__ */ new Set() };
      }
    }
    return result;
  }
});

// src/gutter.ts
var import_view = require("@codemirror/view");
var import_state4 = require("@codemirror/state");

// src/operations.ts
var import_state2 = require("@codemirror/state");

// src/block-utils.ts
function getIndentLevel(line, tabSize, useTab) {
  let level = 0;
  let i = 0;
  if (useTab) {
    while (i < line.length && line[i] === "	") {
      level++;
      i++;
    }
  } else {
    let spaces = 0;
    while (i < line.length && line[i] === " ") {
      spaces++;
      i++;
    }
    level = Math.floor(spaces / tabSize);
  }
  return level;
}
function getLineText(state, lineNumber) {
  return state.doc.line(lineNumber).text;
}
function isBulletItem(text) {
  return /^(\s*)([-*+])\s/.test(text);
}
function isNumberedItem(text) {
  return /^(\s*)\d+\.\s/.test(text);
}
function isCheckboxItem(text) {
  return /^(\s*)([-*+])\s\[[ x]\]\s/.test(text);
}
function getLeadingWhitespace(text) {
  const match = text.match(/^(\s*)/);
  return match ? match[1] : "";
}
function getBlockWithChildren(state, lineNumber, tabSize, useTab) {
  const lineText = getLineText(state, lineNumber);
  const baseIndent = getIndentLevel(lineText, tabSize, useTab);
  const totalLines = state.doc.lines;
  let endLine = lineNumber;
  for (let i = lineNumber + 1; i <= totalLines; i++) {
    const text = getLineText(state, i);
    if (text.trim() === "") {
      let nextNonEmpty = i + 1;
      while (nextNonEmpty <= totalLines && getLineText(state, nextNonEmpty).trim() === "") {
        nextNonEmpty++;
      }
      if (nextNonEmpty <= totalLines && getIndentLevel(getLineText(state, nextNonEmpty), tabSize, useTab) > baseIndent) {
        endLine = i;
        continue;
      }
      break;
    }
    const indent = getIndentLevel(text, tabSize, useTab);
    if (indent > baseIndent) {
      endLine = i;
    } else {
      break;
    }
  }
  return [lineNumber, endLine];
}

// src/operations.ts
var blockEditorTransaction = import_state2.Annotation.define();
function expandWithChildren(view, selectedLines) {
  const doc = view.state.doc;
  const allLines = /* @__PURE__ */ new Set();
  const useTab = true;
  const tabSize = 4;
  const sorted = Array.from(selectedLines).sort((a, b) => a - b);
  for (const lineNum of sorted) {
    if (allLines.has(lineNum))
      continue;
    const [start, end] = getBlockWithChildren(view.state, lineNum, tabSize, useTab);
    for (let i = start; i <= end; i++) {
      allLines.add(i);
    }
  }
  return Array.from(allLines).sort((a, b) => a - b);
}
function moveBlocksUp(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const expanded = expandWithChildren(view, selectedLines);
  const firstLine = expanded[0];
  const lastLine = expanded[expanded.length - 1];
  if (firstLine <= 1)
    return;
  const doc = view.state.doc;
  const lineAbove = doc.line(firstLine - 1);
  const firstSelectedLine = doc.line(firstLine);
  const lastSelectedLine = doc.line(lastLine);
  const aboveText = lineAbove.text;
  const blockTexts = [];
  for (let i = firstLine; i <= lastLine; i++) {
    blockTexts.push(doc.line(i).text);
  }
  const newText = [...blockTexts, aboveText].join("\n");
  const newSelection = new Set(Array.from(selectedLines).map((l) => l - 1));
  view.dispatch({
    changes: { from: lineAbove.from, to: lastSelectedLine.to, insert: newText },
    effects: [setBlockSelection.of(newSelection)],
    annotations: [blockEditorTransaction.of(true)]
  });
}
function moveBlocksDown(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const expanded = expandWithChildren(view, selectedLines);
  const firstLine = expanded[0];
  const lastLine = expanded[expanded.length - 1];
  if (lastLine >= view.state.doc.lines)
    return;
  const doc = view.state.doc;
  const lineBelow = doc.line(lastLine + 1);
  const firstSelectedLine = doc.line(firstLine);
  const belowText = lineBelow.text;
  const blockTexts = [];
  for (let i = firstLine; i <= lastLine; i++) {
    blockTexts.push(doc.line(i).text);
  }
  const newText = [belowText, ...blockTexts].join("\n");
  const newSelection = new Set(Array.from(selectedLines).map((l) => l + 1));
  view.dispatch({
    changes: { from: firstSelectedLine.from, to: lineBelow.to, insert: newText },
    effects: [setBlockSelection.of(newSelection)],
    annotations: [blockEditorTransaction.of(true)]
  });
}
function indentBlocks(view, selectedLines, indentUnit) {
  if (selectedLines.size === 0)
    return;
  const expanded = expandWithChildren(view, selectedLines);
  const changes = [];
  const doc = view.state.doc;
  for (const lineNum of expanded) {
    const line = doc.line(lineNum);
    changes.push({ from: line.from, to: line.from, insert: indentUnit });
  }
  view.dispatch({
    changes,
    annotations: [blockEditorTransaction.of(true)]
  });
}
function outdentBlocks(view, selectedLines, indentUnit) {
  if (selectedLines.size === 0)
    return;
  const expanded = expandWithChildren(view, selectedLines);
  const changes = [];
  const doc = view.state.doc;
  for (const lineNum of expanded) {
    const line = doc.line(lineNum);
    const text = line.text;
    if (text.startsWith("	")) {
      changes.push({ from: line.from, to: line.from + 1, insert: "" });
    } else {
      let spacesToRemove = 0;
      for (let i = 0; i < Math.min(indentUnit.length, text.length); i++) {
        if (text[i] === " ")
          spacesToRemove++;
        else
          break;
      }
      if (spacesToRemove > 0) {
        changes.push({ from: line.from, to: line.from + spacesToRemove, insert: "" });
      }
    }
  }
  if (changes.length > 0) {
    view.dispatch({
      changes,
      annotations: [blockEditorTransaction.of(true)]
    });
  }
}
function setHeadingLevel(view, selectedLines, level) {
  if (selectedLines.size === 0)
    return;
  const doc = view.state.doc;
  const changes = [];
  const sorted = Array.from(selectedLines).sort((a, b) => a - b);
  for (const lineNum of sorted) {
    if (lineNum < 1 || lineNum > doc.lines)
      continue;
    const line = doc.line(lineNum);
    const content = line.text.replace(/^#{1,6}\s+/, "");
    const prefix = level > 0 ? "#".repeat(level) + " " : "";
    const newText = prefix + content;
    if (newText !== line.text) {
      changes.push({ from: line.from, to: line.to, insert: newText });
    }
  }
  if (changes.length > 0) {
    view.dispatch({
      changes,
      annotations: [blockEditorTransaction.of(true)]
    });
  }
}
function toggleBulletList(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const doc = view.state.doc;
  const changes = [];
  const allBullets = Array.from(selectedLines).every((l) => isBulletItem(doc.line(l).text));
  for (const lineNum of selectedLines) {
    const line = doc.line(lineNum);
    const text = line.text;
    const ws = getLeadingWhitespace(text);
    if (allBullets) {
      const newText = text.replace(/^(\s*)([-*+])\s/, "$1");
      changes.push({ from: line.from, to: line.to, insert: newText });
    } else {
      let content = text.replace(/^(\s*)([-*+]|\d+\.)\s(\[[ x]\]\s)?/, "$1");
      changes.push({ from: line.from, to: line.to, insert: ws + "- " + content.trimStart() });
    }
  }
  view.dispatch({
    changes,
    annotations: [blockEditorTransaction.of(true)]
  });
}
function toggleNumberedList(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const doc = view.state.doc;
  const changes = [];
  const allNumbered = Array.from(selectedLines).every((l) => isNumberedItem(doc.line(l).text));
  let counter = 1;
  const sorted = Array.from(selectedLines).sort((a, b) => a - b);
  for (const lineNum of sorted) {
    const line = doc.line(lineNum);
    const text = line.text;
    const ws = getLeadingWhitespace(text);
    if (allNumbered) {
      const newText = text.replace(/^(\s*)\d+\.\s/, "$1");
      changes.push({ from: line.from, to: line.to, insert: newText });
    } else {
      let content = text.replace(/^(\s*)([-*+]|\d+\.)\s(\[[ x]\]\s)?/, "$1");
      changes.push({ from: line.from, to: line.to, insert: ws + counter + ". " + content.trimStart() });
      counter++;
    }
  }
  view.dispatch({
    changes,
    annotations: [blockEditorTransaction.of(true)]
  });
}
function toggleCheckbox(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const doc = view.state.doc;
  const changes = [];
  const allCheckbox = Array.from(selectedLines).every((l) => isCheckboxItem(doc.line(l).text));
  for (const lineNum of selectedLines) {
    const line = doc.line(lineNum);
    const text = line.text;
    const ws = getLeadingWhitespace(text);
    if (allCheckbox) {
      const newText = text.replace(/^(\s*)([-*+])\s\[[ x]\]\s/, "$1$2 ");
      changes.push({ from: line.from, to: line.to, insert: newText });
    } else {
      let content = text.replace(/^(\s*)([-*+]|\d+\.)\s(\[[ x]\]\s)?/, "$1");
      changes.push({ from: line.from, to: line.to, insert: ws + "- [ ] " + content.trimStart() });
    }
  }
  view.dispatch({
    changes,
    annotations: [blockEditorTransaction.of(true)]
  });
}
function deleteBlocks(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const expanded = expandWithChildren(view, selectedLines);
  const doc = view.state.doc;
  const changes = [];
  for (const lineNum of expanded) {
    const line = doc.line(lineNum);
    let from = line.from;
    let to = line.to;
    if (to < doc.length) {
      to += 1;
    } else if (from > 0) {
      from -= 1;
    }
    changes.push({ from, to, insert: "" });
  }
  view.dispatch({
    changes,
    effects: [setBlockSelection.of(/* @__PURE__ */ new Set())],
    annotations: [blockEditorTransaction.of(true)]
  });
}
function undoAction(view) {
  const commands = require("@codemirror/commands");
  commands.undo(view);
}
function redoAction(view) {
  const commands = require("@codemirror/commands");
  commands.redo(view);
}
function copyBlocks(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const expanded = expandWithChildren(view, selectedLines);
  const doc = view.state.doc;
  const lines = expanded.map((l) => doc.line(l).text);
  const text = lines.join("\n");
  navigator.clipboard.writeText(text);
}
function cutBlocks(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  copyBlocks(view, selectedLines);
  deleteBlocks(view, selectedLines);
}
function toggleQuote(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const doc = view.state.doc;
  const changes = [];
  const allQuoted = Array.from(selectedLines).every(
    (l) => doc.line(l).text.startsWith("> ")
  );
  for (const lineNum of selectedLines) {
    const line = doc.line(lineNum);
    const text = line.text;
    if (allQuoted) {
      changes.push({ from: line.from, to: line.to, insert: text.replace(/^> /, "") });
    } else {
      changes.push({ from: line.from, to: line.to, insert: "> " + text });
    }
  }
  view.dispatch({
    changes,
    annotations: [blockEditorTransaction.of(true)]
  });
}
function getFrontmatterEndForOps(view) {
  const doc = view.state.doc;
  if (doc.lines < 1)
    return 0;
  if (doc.line(1).text.trim() !== "---")
    return 0;
  for (let i = 2; i <= doc.lines; i++) {
    if (doc.line(i).text.trim() === "---")
      return i;
  }
  return 0;
}
function progressiveSelectAll(view, selectedLines) {
  const doc = view.state.doc;
  const frontmatterEnd = getFrontmatterEndForOps(view);
  const useTab = true;
  const tabSize = 4;
  if (selectedLines.size === 0) {
    const allLines2 = /* @__PURE__ */ new Set();
    for (let i = frontmatterEnd + 1; i <= doc.lines; i++) {
      if (doc.line(i).text.trim() !== "")
        allLines2.add(i);
    }
    view.dispatch({ effects: [setBlockSelection.of(allLines2)] });
    return;
  }
  const sorted = Array.from(selectedLines).sort((a, b) => a - b);
  const withChildren = /* @__PURE__ */ new Set();
  for (const lineNum of sorted) {
    const [start, end] = getBlockWithChildren(view.state, lineNum, tabSize, useTab);
    for (let i = start; i <= end; i++) {
      if (doc.line(i).text.trim() !== "")
        withChildren.add(i);
    }
  }
  if (withChildren.size > selectedLines.size) {
    view.dispatch({ effects: [setBlockSelection.of(withChildren)] });
    return;
  }
  const firstSelected = sorted[0];
  const firstText = doc.line(firstSelected).text;
  const firstIndent = getIndentLevel(firstText, tabSize, useTab);
  let listStart = firstSelected;
  for (let i = firstSelected - 1; i > frontmatterEnd; i--) {
    const text = doc.line(i).text;
    if (text.trim() === "") {
      if (i > frontmatterEnd + 1) {
        const above = doc.line(i - 1).text;
        if (isBulletItem(above) || isNumberedItem(above) || isCheckboxItem(above)) {
          listStart = i;
          continue;
        }
      }
      break;
    }
    if (isBulletItem(text) || isNumberedItem(text) || isCheckboxItem(text)) {
      listStart = i;
    } else {
      listStart = i;
      break;
    }
  }
  let listEnd = sorted[sorted.length - 1];
  for (let i = listEnd + 1; i <= doc.lines; i++) {
    const text = doc.line(i).text;
    if (text.trim() === "") {
      let nextNonEmpty = i + 1;
      while (nextNonEmpty <= doc.lines && doc.line(nextNonEmpty).text.trim() === "") {
        nextNonEmpty++;
      }
      if (nextNonEmpty <= doc.lines) {
        const nextText = doc.line(nextNonEmpty).text;
        if (isBulletItem(nextText) || isNumberedItem(nextText) || isCheckboxItem(nextText)) {
          listEnd = i;
          continue;
        }
      }
      break;
    }
    if (isBulletItem(text) || isNumberedItem(text) || isCheckboxItem(text) || getIndentLevel(text, tabSize, useTab) > 0) {
      listEnd = i;
    } else {
      break;
    }
  }
  const listSelection = /* @__PURE__ */ new Set();
  for (let i = listStart; i <= listEnd; i++) {
    if (doc.line(i).text.trim() !== "")
      listSelection.add(i);
  }
  if (listSelection.size > selectedLines.size) {
    view.dispatch({ effects: [setBlockSelection.of(listSelection)] });
    return;
  }
  const allLines = /* @__PURE__ */ new Set();
  for (let i = frontmatterEnd + 1; i <= doc.lines; i++) {
    if (doc.line(i).text.trim() !== "")
      allLines.add(i);
  }
  view.dispatch({ effects: [setBlockSelection.of(allLines)] });
}

// src/gutter.ts
function getFrontmatterEnd(view) {
  const doc = view.state.doc;
  if (doc.lines < 1)
    return 0;
  if (doc.line(1).text.trim() !== "---")
    return 0;
  for (let i = 2; i <= doc.lines; i++) {
    if (doc.line(i).text.trim() === "---")
      return i;
  }
  return 0;
}
var blockModeTransactionFilter = import_state4.EditorState.transactionFilter.of((tr) => {
  const state = tr.startState.field(blockSelectionState);
  if (!state.active)
    return tr;
  if (tr.annotation(blockEditorTransaction))
    return tr;
  if (tr.effects.length > 0)
    return tr;
  if (tr.docChanged) {
    const userEvent = tr.annotation(import_state4.Transaction.userEvent);
    if (userEvent)
      return [];
    return tr;
  }
  return tr;
});
var blockSelectionGutter = import_view.ViewPlugin.fromClass(
  class {
    constructor(view) {
      this.view = view;
      this.container = document.createElement("div");
      this.container.className = "block-editor-gutter";
      this.container.style.display = "none";
      document.body.appendChild(this.container);
      this.scrollHandler = () => {
        if (this.view.state.field(blockSelectionState).active) {
          this.buildGutter();
        }
      };
      view.scrollDOM.addEventListener("scroll", this.scrollHandler);
      this.focusHandler = () => {
        if (this.view.state.field(blockSelectionState).active) {
          setTimeout(() => this.view.contentDOM.blur(), 0);
        }
      };
      view.contentDOM.addEventListener("focus", this.focusHandler);
      this.contentPointerHandler = (e) => {
        if (!this.view.state.field(blockSelectionState).active)
          return;
        if (e.target.closest(".block-editor-gutter-circle"))
          return;
        const pos = this.view.posAtCoords({ x: e.clientX, y: e.clientY });
        if (pos === null)
          return;
        const lineNum = this.view.state.doc.lineAt(pos).number;
        const frontmatterEnd = getFrontmatterEnd(this.view);
        if (lineNum <= frontmatterEnd)
          return;
        e.preventDefault();
        this.toggleLineWithChildren(lineNum);
      };
      view.contentDOM.addEventListener("pointerdown", this.contentPointerHandler);
    }
    update(update) {
      const state = update.state.field(blockSelectionState);
      const prev = update.startState.field(blockSelectionState);
      if (state.active && !prev.active) {
        this.view.contentDOM.blur();
      }
      if (state.active !== prev.active || state.selectedBlocks !== prev.selectedBlocks || update.docChanged || update.viewportChanged || update.geometryChanged) {
        this.buildGutter();
      }
    }
    /**
     * Toggle selection for a line and its children.
     * Selecting a parent auto-selects all indented children below it.
     * If the parent+children are already all selected, deselect them all.
     */
    toggleLineWithChildren(lineNum) {
      const state = this.view.state.field(blockSelectionState);
      const [start, end] = getBlockWithChildren(this.view.state, lineNum, 4, true);
      const newSet = new Set(state.selectedBlocks);
      let allSelected = true;
      for (let i = start; i <= end; i++) {
        const lineText = this.view.state.doc.line(i).text;
        if (lineText.trim() === "")
          continue;
        if (!newSet.has(i)) {
          allSelected = false;
          break;
        }
      }
      if (allSelected) {
        for (let i = start; i <= end; i++) {
          newSet.delete(i);
        }
      } else {
        for (let i = start; i <= end; i++) {
          const lineText = this.view.state.doc.line(i).text;
          if (lineText.trim() === "")
            continue;
          newSet.add(i);
        }
      }
      this.view.dispatch({
        effects: [setBlockSelection.of(newSet)]
      });
    }
    buildGutter() {
      const state = this.view.state.field(blockSelectionState);
      this.container.innerHTML = "";
      if (!state.active) {
        this.container.style.display = "none";
        return;
      }
      this.container.style.display = "block";
      const frontmatterEnd = getFrontmatterEnd(this.view);
      const { from, to } = this.view.viewport;
      const doc = this.view.state.doc;
      const startLine = doc.lineAt(from).number;
      const endLine = doc.lineAt(to).number;
      const contentTop = this.view.contentDOM.getBoundingClientRect().top;
      const scrollerRect = this.view.scrollDOM.getBoundingClientRect();
      const circleLeft = scrollerRect.right - 44;
      for (let lineNum = startLine; lineNum <= endLine; lineNum++) {
        if (lineNum <= frontmatterEnd)
          continue;
        const line = doc.line(lineNum);
        if (line.text.trim() === "")
          continue;
        const block = this.view.lineBlockAt(line.from);
        const screenY = contentTop + block.top;
        if (screenY + block.height < scrollerRect.top)
          continue;
        if (screenY > scrollerRect.bottom)
          continue;
        const circle = document.createElement("div");
        circle.className = "block-editor-gutter-circle";
        if (state.selectedBlocks.has(lineNum)) {
          circle.classList.add("selected");
        }
        circle.style.top = screenY + (block.height - 20) / 2 + "px";
        circle.style.left = circleLeft + "px";
        circle.addEventListener("pointerdown", (e) => {
          e.preventDefault();
          e.stopPropagation();
          this.toggleLineWithChildren(lineNum);
        });
        circle.addEventListener("mousedown", (e) => {
          e.preventDefault();
          e.stopPropagation();
        });
        circle.addEventListener("touchstart", (e) => {
          e.preventDefault();
          e.stopPropagation();
        }, { passive: false });
        this.container.appendChild(circle);
      }
    }
    destroy() {
      this.container.remove();
      this.view.scrollDOM.removeEventListener("scroll", this.scrollHandler);
      this.view.contentDOM.removeEventListener("focus", this.focusHandler);
      this.view.contentDOM.removeEventListener("pointerdown", this.contentPointerHandler);
    }
  }
);

// src/highlighter.ts
var import_view2 = require("@codemirror/view");
var import_state6 = require("@codemirror/state");
var blockHighlighter = import_view2.ViewPlugin.fromClass(
  class {
    constructor(view) {
      this.view = view;
      this.decorations = this.buildDecorations();
    }
    update(update) {
      const state = update.state.field(blockSelectionState);
      const prevState = update.startState.field(blockSelectionState);
      if (state.active !== prevState.active || state.selectedBlocks !== prevState.selectedBlocks || update.docChanged || update.viewportChanged) {
        this.decorations = this.buildDecorations();
      }
    }
    buildDecorations() {
      const state = this.view.state.field(blockSelectionState);
      if (!state.active || state.selectedBlocks.size === 0) {
        return import_view2.Decoration.none;
      }
      const builder = new import_state6.RangeSetBuilder();
      const lineDeco = import_view2.Decoration.line({ class: "block-editor-selected-line" });
      const sorted = Array.from(state.selectedBlocks).sort((a, b) => a - b);
      const doc = this.view.state.doc;
      for (const lineNum of sorted) {
        if (lineNum >= 1 && lineNum <= doc.lines) {
          const line = doc.line(lineNum);
          builder.add(line.from, line.from, lineDeco);
        }
      }
      return builder.finish();
    }
  },
  {
    decorations: (v) => v.decorations
  }
);

// src/toolbar.ts
var import_obsidian = require("obsidian");
var BlockEditorToolbar = class {
  constructor(indentUnit) {
    this.headingPopup = null;
    this.headingPopupCloseHandler = null;
    this.view = null;
    this.indentUnit = indentUnit;
    this.el = document.createElement("div");
    this.el.className = "block-editor-toolbar";
    this.el.style.display = "none";
    this.buildToolbar();
    this.el.addEventListener("pointerdown", (e) => e.preventDefault());
  }
  setView(view) {
    this.view = view;
  }
  setIndentUnit(unit) {
    this.indentUnit = unit;
  }
  buildToolbar() {
    const topRow = [
      { icon: "undo-2", title: "Undo", action: () => this.doUndo() },
      { icon: "redo-2", title: "Redo", action: () => this.doRedo() },
      { icon: "check-check", title: "Select All", action: () => this.doSelectAll() },
      { icon: "scissors", title: "Cut", action: () => this.doCut() },
      { icon: "copy", title: "Copy", action: () => this.doCopy() },
      "separator",
      { icon: "outdent", title: "Outdent", action: () => this.doOutdent() },
      { icon: "indent", title: "Indent", action: () => this.doIndent() },
      { icon: "arrow-up", title: "Move Up", action: () => this.doAction(moveBlocksUp) },
      { icon: "arrow-down", title: "Move Down", action: () => this.doAction(moveBlocksDown) }
    ];
    const bottomRow = [
      { icon: "heading", title: "Heading", action: () => this.showHeadingPopup() },
      { icon: "list", title: "Bullet List", action: () => this.doAction(toggleBulletList) },
      { icon: "list-ordered", title: "Numbered List", action: () => this.doAction(toggleNumberedList) },
      { icon: "check-square", title: "Checkbox", action: () => this.doAction(toggleCheckbox) },
      { icon: "text-quote", title: "Quote", action: () => this.doAction(toggleQuote) },
      "separator",
      { icon: "trash-2", title: "Delete", action: () => this.doDelete(), className: "block-editor-btn-danger" }
    ];
    this.el.appendChild(this.buildRow(topRow));
    this.el.appendChild(this.buildRow(bottomRow));
  }
  buildRow(items) {
    const row = document.createElement("div");
    row.className = "block-editor-toolbar-row";
    for (const item of items) {
      if (item === "separator") {
        const sep = document.createElement("div");
        sep.className = "block-editor-toolbar-separator";
        row.appendChild(sep);
        continue;
      }
      const btn = document.createElement("button");
      btn.setAttribute("aria-label", item.title);
      btn.title = item.title;
      if (item.className)
        btn.classList.add(item.className);
      (0, import_obsidian.setIcon)(btn, item.icon);
      btn.addEventListener("pointerup", (e) => {
        e.preventDefault();
        e.stopPropagation();
        item.action();
      });
      row.appendChild(btn);
    }
    return row;
  }
  getSelectedLines() {
    if (!this.view)
      return null;
    const state = this.view.state.field(blockSelectionState);
    if (!state.active || state.selectedBlocks.size === 0)
      return null;
    return state.selectedBlocks;
  }
  doAction(fn) {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    fn(this.view, selected);
  }
  doIndent() {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    indentBlocks(this.view, selected, this.indentUnit);
  }
  doOutdent() {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    outdentBlocks(this.view, selected, this.indentUnit);
  }
  doDelete() {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    deleteBlocks(this.view, selected);
  }
  doUndo() {
    if (!this.view)
      return;
    undoAction(this.view);
  }
  doRedo() {
    if (!this.view)
      return;
    redoAction(this.view);
  }
  doCopy() {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    copyBlocks(this.view, selected);
  }
  doCut() {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    cutBlocks(this.view, selected);
  }
  doSelectAll() {
    if (!this.view)
      return;
    const state = this.view.state.field(blockSelectionState);
    progressiveSelectAll(this.view, state.selectedBlocks);
  }
  showHeadingPopup() {
    if (this.headingPopup) {
      this.headingPopup.remove();
      this.headingPopup = null;
      return;
    }
    const popup = document.createElement("div");
    popup.className = "block-editor-heading-popup";
    popup.addEventListener("pointerdown", (e) => e.preventDefault());
    const options = [
      { label: "Body", level: 0 },
      { label: "H1", level: 1 },
      { label: "H2", level: 2 },
      { label: "H3", level: 3 },
      { label: "H4", level: 4 },
      { label: "H5", level: 5 },
      { label: "H6", level: 6 }
    ];
    for (const opt of options) {
      const btn = document.createElement("button");
      btn.textContent = opt.label;
      btn.addEventListener("pointerup", (e) => {
        e.preventDefault();
        e.stopPropagation();
        const selected = this.getSelectedLines();
        if (selected && this.view) {
          setHeadingLevel(this.view, selected, opt.level);
        }
        this.hideHeadingPopup();
      });
      popup.appendChild(btn);
    }
    popup.style.bottom = this.el.offsetHeight + 8 + "px";
    popup.style.left = "50%";
    popup.style.transform = "translateX(-50%)";
    document.body.appendChild(popup);
    this.headingPopup = popup;
    this.headingPopupCloseHandler = (e) => {
      if (!popup.contains(e.target) && !this.el.contains(e.target)) {
        this.hideHeadingPopup();
      }
    };
    const handler = this.headingPopupCloseHandler;
    setTimeout(() => document.addEventListener("pointerdown", handler), 0);
  }
  hideHeadingPopup() {
    if (this.headingPopupCloseHandler) {
      document.removeEventListener("pointerdown", this.headingPopupCloseHandler);
      this.headingPopupCloseHandler = null;
    }
    if (this.headingPopup) {
      this.headingPopup.remove();
      this.headingPopup = null;
    }
  }
  show() {
    this.el.style.display = "flex";
  }
  hide() {
    this.el.style.display = "none";
    this.hideHeadingPopup();
  }
  destroy() {
    this.el.remove();
    this.hideHeadingPopup();
  }
  updateVisibility(active, hasSelection) {
    if (active && hasSelection) {
      this.show();
    } else {
      this.hide();
    }
  }
};

// src/fab.ts
var import_obsidian2 = require("obsidian");
var BlockEditorFAB = class {
  constructor() {
    this.view = null;
    this.el = document.createElement("button");
    this.el.className = "block-editor-fab";
    this.el.setAttribute("aria-label", "Toggle Block Mode");
    (0, import_obsidian2.setIcon)(this.el, "layout-grid");
    this.el.addEventListener("pointerdown", (e) => {
      e.preventDefault();
      e.stopPropagation();
      this.toggle();
    });
    this.el.addEventListener("mousedown", (e) => e.preventDefault());
    this.el.addEventListener("touchstart", (e) => e.preventDefault(), { passive: false });
  }
  setView(view) {
    this.view = view;
  }
  toggle() {
    if (!this.view)
      return;
    const state = this.view.state.field(blockSelectionState);
    const newActive = !state.active;
    if (newActive) {
      const cursorPos = this.view.state.selection.main.head;
      const cursorLine = this.view.state.doc.lineAt(cursorPos).number;
      const [start, end] = getBlockWithChildren(this.view.state, cursorLine, 4, true);
      const selected = /* @__PURE__ */ new Set();
      for (let i = start; i <= end; i++) {
        if (this.view.state.doc.line(i).text.trim() !== "") {
          selected.add(i);
        }
      }
      this.view.dispatch({
        effects: [toggleBlockMode.of(true), setBlockSelection.of(selected)]
      });
      this.view.contentDOM.blur();
    } else {
      this.view.dispatch({
        effects: [toggleBlockMode.of(false)]
      });
    }
    this.updateAppearance(newActive);
  }
  updateAppearance(active) {
    if (active) {
      this.el.classList.add("active");
      (0, import_obsidian2.setIcon)(this.el, "x");
    } else {
      this.el.classList.remove("active");
      (0, import_obsidian2.setIcon)(this.el, "layout-grid");
    }
  }
  show() {
    this.el.style.display = "flex";
  }
  hide() {
    this.el.style.display = "none";
  }
  destroy() {
    this.el.remove();
  }
};

// src/styles.ts
function injectStyles() {
  const style = document.createElement("style");
  style.id = "block-editor-styles";
  style.textContent = `
/* Gutter: invisible wrapper on document.body */
.block-editor-gutter {
	position: fixed;
	top: 0;
	left: 0;
	width: 0;
	height: 0;
	z-index: 5;
	pointer-events: none;
}

/* Each circle is position:fixed with its own top/left */
.block-editor-gutter-circle {
	position: fixed;
	width: 20px;
	height: 20px;
	border-radius: 50%;
	border: 2px solid var(--interactive-accent);
	background: var(--background-primary);
	cursor: pointer;
	pointer-events: auto;
	transition: background-color 0.15s ease, transform 0.1s ease;
	box-sizing: border-box;
	z-index: 5;
}

.block-editor-gutter-circle:active {
	transform: scale(0.9);
}

.block-editor-gutter-circle.selected {
	background: var(--interactive-accent);
}

/* Line highlight decoration */
.cm-line.block-editor-selected-line {
	background-color: rgba(72, 120, 208, 0.15) !important;
}

/* Toolbar \u2014 2 rows */
.block-editor-toolbar {
	position: fixed;
	bottom: 0;
	left: 0;
	right: 0;
	background: var(--background-primary);
	border-top: 1px solid var(--background-modifier-border);
	display: flex;
	flex-direction: column;
	align-items: center;
	padding: 4px 8px;
	padding-bottom: calc(4px + env(safe-area-inset-bottom, 0px));
	z-index: 100;
	box-shadow: 0 -2px 10px rgba(0, 0, 0, 0.1);
}

.block-editor-toolbar-row {
	display: flex;
	align-items: center;
	justify-content: center;
	gap: 2px;
	width: 100%;
	padding: 2px 0;
}

.block-editor-toolbar button {
	display: flex;
	align-items: center;
	justify-content: center;
	width: 36px;
	height: 36px;
	border: none;
	border-radius: var(--radius-s);
	background: var(--background-secondary);
	color: var(--text-normal);
	cursor: pointer;
	padding: 0;
	touch-action: manipulation;
	flex-shrink: 0;
}

.block-editor-toolbar button:active {
	background: var(--interactive-accent);
	color: var(--text-on-accent);
}

.block-editor-toolbar button.block-editor-btn-danger {
	color: var(--text-error);
}

.block-editor-toolbar button.block-editor-btn-danger:active {
	background: var(--text-error);
	color: var(--text-on-accent);
}

.block-editor-toolbar button .svg-icon {
	width: 18px;
	height: 18px;
}

.block-editor-toolbar-separator {
	width: 1px;
	height: 24px;
	background: var(--background-modifier-border);
	margin: 0 2px;
	flex-shrink: 0;
}

/* Heading popup */
.block-editor-heading-popup {
	position: fixed;
	background: var(--background-primary);
	border: 1px solid var(--background-modifier-border);
	border-radius: var(--radius-s);
	box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
	z-index: 200;
	display: flex;
	flex-direction: column;
	padding: 4px;
}

.block-editor-heading-popup button {
	display: flex;
	align-items: center;
	justify-content: flex-start;
	padding: 6px 12px;
	border: none;
	background: transparent;
	color: var(--text-normal);
	cursor: pointer;
	border-radius: var(--radius-s);
	font-size: 14px;
	touch-action: manipulation;
	width: auto;
}

.block-editor-heading-popup button:active {
	background: var(--interactive-accent);
	color: var(--text-on-accent);
}

/* FAB */
.block-editor-fab {
	position: fixed;
	bottom: calc(60px + env(safe-area-inset-bottom, 0px));
	right: 16px;
	width: 48px;
	height: 48px;
	border-radius: 50%;
	background: var(--interactive-accent);
	color: var(--text-on-accent);
	border: none;
	box-shadow: 0 4px 12px rgba(0, 0, 0, 0.25);
	cursor: pointer;
	display: flex;
	align-items: center;
	justify-content: center;
	z-index: 50;
	touch-action: manipulation;
	transition: transform 0.15s ease;
}

.block-editor-fab:active {
	transform: scale(0.9);
}

.block-editor-fab .svg-icon {
	width: 22px;
	height: 22px;
}

.block-editor-fab.toolbar-visible {
	bottom: calc(100px + env(safe-area-inset-bottom, 0px));
}

.block-editor-fab.active {
	background: var(--text-error);
}
`;
  document.head.appendChild(style);
  return style;
}
function removeStyles() {
  const el = document.getElementById("block-editor-styles");
  if (el)
    el.remove();
}

// src/main.ts
var BlockEditorPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.toolbar = null;
    this.fab = null;
    this.styleEl = null;
  }
  async onload() {
    var _a, _b, _c, _d, _e, _f;
    this.styleEl = injectStyles();
    const useTab = (_c = (_b = (_a = this.app.vault).getConfig) == null ? void 0 : _b.call(_a, "useTab")) != null ? _c : true;
    const tabSize = (_f = (_e = (_d = this.app.vault).getConfig) == null ? void 0 : _e.call(_d, "tabSize")) != null ? _f : 4;
    const indentUnit = useTab ? "	" : " ".repeat(tabSize);
    this.toolbar = new BlockEditorToolbar(indentUnit);
    this.fab = new BlockEditorFAB();
    document.body.appendChild(this.toolbar.el);
    document.body.appendChild(this.fab.el);
    const toolbar = this.toolbar;
    const fab = this.fab;
    const connectorPlugin = import_view3.ViewPlugin.fromClass(
      class {
        constructor(view) {
          this.view = view;
          toolbar.setView(view);
          fab.setView(view);
          this.syncState();
        }
        update(update) {
          toolbar.setView(this.view);
          fab.setView(this.view);
          this.syncState();
        }
        syncState() {
          const state = this.view.state.field(blockSelectionState);
          const hasSelection = state.selectedBlocks.size > 0;
          toolbar.updateVisibility(state.active, hasSelection);
          fab.updateAppearance(state.active);
          if (state.active && hasSelection) {
            fab.el.classList.add("toolbar-visible");
          } else {
            fab.el.classList.remove("toolbar-visible");
          }
        }
        destroy() {
          toolbar.hide();
        }
      }
    );
    this.registerEditorExtension([
      blockSelectionState,
      blockModeTransactionFilter,
      blockSelectionGutter,
      blockHighlighter,
      connectorPlugin
    ]);
    const toggleBlock = (editor) => {
      const cmEditor = editor.cm;
      if (!cmEditor)
        return;
      const state = cmEditor.state.field(blockSelectionState);
      const newActive = !state.active;
      if (newActive) {
        const cursorPos = cmEditor.state.selection.main.head;
        const cursorLine = cmEditor.state.doc.lineAt(cursorPos).number;
        const [start, end] = getBlockWithChildren(cmEditor.state, cursorLine, 4, true);
        const selected = /* @__PURE__ */ new Set();
        for (let i = start; i <= end; i++) {
          if (cmEditor.state.doc.line(i).text.trim() !== "") {
            selected.add(i);
          }
        }
        cmEditor.dispatch({
          effects: [toggleBlockMode.of(true), setBlockSelection.of(selected)]
        });
        cmEditor.contentDOM.blur();
      } else {
        cmEditor.dispatch({
          effects: [toggleBlockMode.of(false)]
        });
      }
    };
    this.addCommand({
      id: "toggle-block-mode",
      name: "Toggle Block Mode",
      icon: "layout-grid",
      editorCallback: toggleBlock
    });
    this.addRibbonIcon("layout-grid", "Toggle Block Mode", () => {
      const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
      if (markdownView) {
        toggleBlock(markdownView.editor);
      }
    });
  }
  onunload() {
    var _a, _b;
    (_a = this.toolbar) == null ? void 0 : _a.destroy();
    (_b = this.fab) == null ? void 0 : _b.destroy();
    removeStyles();
  }
};
