/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BlockEditorPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");
var import_view3 = require("@codemirror/view");

// src/state.ts
var import_state = require("@codemirror/state");
var toggleBlockMode = import_state.StateEffect.define();
var toggleBlockSelection = import_state.StateEffect.define();
var setBlockSelection = import_state.StateEffect.define();
var clearBlockSelection = import_state.StateEffect.define();
var blockSelectionState = import_state.StateField.define({
  create() {
    return { active: false, selectedBlocks: /* @__PURE__ */ new Set() };
  },
  update(value, tr) {
    let result = value;
    for (const effect of tr.effects) {
      if (effect.is(toggleBlockMode)) {
        result = {
          active: effect.value,
          selectedBlocks: /* @__PURE__ */ new Set()
        };
      } else if (effect.is(toggleBlockSelection)) {
        const newSet = new Set(result.selectedBlocks);
        if (newSet.has(effect.value)) {
          newSet.delete(effect.value);
        } else {
          newSet.add(effect.value);
        }
        result = { active: result.active, selectedBlocks: newSet };
      } else if (effect.is(setBlockSelection)) {
        result = { active: result.active, selectedBlocks: effect.value };
      } else if (effect.is(clearBlockSelection)) {
        result = { active: result.active, selectedBlocks: /* @__PURE__ */ new Set() };
      }
    }
    return result;
  }
});

// src/gutter.ts
var import_view = require("@codemirror/view");
var import_state4 = require("@codemirror/state");

// src/operations.ts
var import_state2 = require("@codemirror/state");

// src/block-utils.ts
function getIndentLevel(line, tabSize, useTab) {
  let level = 0;
  let i = 0;
  if (useTab) {
    while (i < line.length && line[i] === "	") {
      level++;
      i++;
    }
  } else {
    let spaces = 0;
    while (i < line.length && line[i] === " ") {
      spaces++;
      i++;
    }
    level = Math.floor(spaces / tabSize);
  }
  return level;
}
function getLineText(state, lineNumber) {
  return state.doc.line(lineNumber).text;
}
function isBulletItem(text) {
  return /^(\s*)([-*+])\s/.test(text);
}
function isNumberedItem(text) {
  return /^(\s*)\d+\.\s/.test(text);
}
function isCheckboxItem(text) {
  return /^(\s*)([-*+])\s\[[ x]\]\s/.test(text);
}
function getLeadingWhitespace(text) {
  const match = text.match(/^(\s*)/);
  return match ? match[1] : "";
}
function getBlockWithChildren(state, lineNumber, tabSize, useTab) {
  const lineText = getLineText(state, lineNumber);
  const baseIndent = getIndentLevel(lineText, tabSize, useTab);
  const totalLines = state.doc.lines;
  let endLine = lineNumber;
  for (let i = lineNumber + 1; i <= totalLines; i++) {
    const text = getLineText(state, i);
    if (text.trim() === "") {
      let nextNonEmpty = i + 1;
      while (nextNonEmpty <= totalLines && getLineText(state, nextNonEmpty).trim() === "") {
        nextNonEmpty++;
      }
      if (nextNonEmpty <= totalLines && getIndentLevel(getLineText(state, nextNonEmpty), tabSize, useTab) > baseIndent) {
        endLine = i;
        continue;
      }
      break;
    }
    const indent = getIndentLevel(text, tabSize, useTab);
    if (indent > baseIndent) {
      endLine = i;
    } else {
      break;
    }
  }
  return [lineNumber, endLine];
}

// src/operations.ts
var blockEditorTransaction = import_state2.Annotation.define();
function expandWithChildren(view, selectedLines) {
  const doc = view.state.doc;
  const allLines = /* @__PURE__ */ new Set();
  const useTab = true;
  const tabSize = 4;
  const sorted = Array.from(selectedLines).sort((a, b) => a - b);
  for (const lineNum of sorted) {
    if (allLines.has(lineNum))
      continue;
    const [start, end] = getBlockWithChildren(view.state, lineNum, tabSize, useTab);
    for (let i = start; i <= end; i++) {
      allLines.add(i);
    }
  }
  return Array.from(allLines).sort((a, b) => a - b);
}
function moveBlocksUp(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const expanded = expandWithChildren(view, selectedLines);
  const firstLine = expanded[0];
  const lastLine = expanded[expanded.length - 1];
  if (firstLine <= 1)
    return;
  const doc = view.state.doc;
  const lineAbove = doc.line(firstLine - 1);
  const frontmatterEnd = getFrontmatterEndForOps(view);
  if (frontmatterEnd > 0 && firstLine - 1 <= frontmatterEnd)
    return;
  const firstSelectedLine = doc.line(firstLine);
  const lastSelectedLine = doc.line(lastLine);
  const useTab = true;
  const tabSize = 4;
  const indentStr = useTab ? "	" : " ".repeat(tabSize);
  const targetIndent = getIndentLevel(lineAbove.text, tabSize, useTab);
  const currentIndent = getIndentLevel(firstSelectedLine.text, tabSize, useTab);
  if (targetIndent > currentIndent) {
    const indentDelta2 = targetIndent - currentIndent;
    const blockTexts2 = [];
    for (let i = firstLine; i <= lastLine; i++) {
      blockTexts2.push(indentStr.repeat(indentDelta2) + doc.line(i).text);
    }
    const newText2 = blockTexts2.join("\n");
    view.dispatch({
      changes: { from: firstSelectedLine.from, to: lastSelectedLine.to, insert: newText2 },
      annotations: [blockEditorTransaction.of(true)]
    });
    return;
  }
  const indentDelta = targetIndent - currentIndent;
  const blockTexts = [];
  for (let i = firstLine; i <= lastLine; i++) {
    let text = doc.line(i).text;
    if (indentDelta < 0) {
      for (let d = 0; d < -indentDelta; d++) {
        if (text.startsWith("	")) {
          text = text.slice(1);
        } else if (text.startsWith(" ".repeat(tabSize))) {
          text = text.slice(tabSize);
        }
      }
    }
    blockTexts.push(text);
  }
  const newText = [...blockTexts, lineAbove.text].join("\n");
  const newSelection = new Set(Array.from(selectedLines).map((l) => l - 1));
  view.dispatch({
    changes: { from: lineAbove.from, to: lastSelectedLine.to, insert: newText },
    effects: [setBlockSelection.of(newSelection)],
    annotations: [blockEditorTransaction.of(true)]
  });
}
function moveBlocksDown(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const expanded = expandWithChildren(view, selectedLines);
  const firstLine = expanded[0];
  const lastLine = expanded[expanded.length - 1];
  if (lastLine >= view.state.doc.lines)
    return;
  const doc = view.state.doc;
  const lineBelow = doc.line(lastLine + 1);
  const firstSelectedLine = doc.line(firstLine);
  const lastSelectedLine = doc.line(lastLine);
  const useTab = true;
  const tabSize = 4;
  const indentStr = useTab ? "	" : " ".repeat(tabSize);
  const belowIndent = getIndentLevel(lineBelow.text, tabSize, useTab);
  const currentIndent = getIndentLevel(firstSelectedLine.text, tabSize, useTab);
  if (currentIndent > belowIndent) {
    const blockTexts2 = [];
    for (let i = firstLine; i <= lastLine; i++) {
      let text = doc.line(i).text;
      if (text.startsWith("	")) {
        text = text.slice(1);
      } else if (text.startsWith(" ".repeat(tabSize))) {
        text = text.slice(tabSize);
      }
      blockTexts2.push(text);
    }
    view.dispatch({
      changes: { from: firstSelectedLine.from, to: lastSelectedLine.to, insert: blockTexts2.join("\n") },
      annotations: [blockEditorTransaction.of(true)]
    });
    return;
  }
  let belowHasChildren = false;
  if (lastLine + 2 <= doc.lines) {
    const lineBelowNext = doc.line(lastLine + 2);
    if (lineBelowNext.text.trim() !== "" && getIndentLevel(lineBelowNext.text, tabSize, useTab) > belowIndent) {
      belowHasChildren = true;
    }
  }
  const targetIndent = belowHasChildren && currentIndent <= belowIndent ? belowIndent + 1 : belowIndent;
  const indentDelta = targetIndent - currentIndent;
  const blockTexts = [];
  for (let i = firstLine; i <= lastLine; i++) {
    let text = doc.line(i).text;
    if (indentDelta > 0) {
      text = indentStr.repeat(indentDelta) + text;
    }
    blockTexts.push(text);
  }
  const newText = [lineBelow.text, ...blockTexts].join("\n");
  const newSelection = new Set(Array.from(selectedLines).map((l) => l + 1));
  view.dispatch({
    changes: { from: firstSelectedLine.from, to: lineBelow.to, insert: newText },
    effects: [setBlockSelection.of(newSelection)],
    annotations: [blockEditorTransaction.of(true)]
  });
}
function indentBlocks(view, selectedLines, indentUnit) {
  if (selectedLines.size === 0)
    return;
  const expanded = expandWithChildren(view, selectedLines);
  const changes = [];
  const doc = view.state.doc;
  for (const lineNum of expanded) {
    const line = doc.line(lineNum);
    changes.push({ from: line.from, to: line.from, insert: indentUnit });
  }
  view.dispatch({
    changes,
    annotations: [blockEditorTransaction.of(true)]
  });
}
function outdentBlocks(view, selectedLines, indentUnit) {
  if (selectedLines.size === 0)
    return;
  const expanded = expandWithChildren(view, selectedLines);
  const changes = [];
  const doc = view.state.doc;
  for (const lineNum of expanded) {
    const line = doc.line(lineNum);
    const text = line.text;
    if (text.startsWith("	")) {
      changes.push({ from: line.from, to: line.from + 1, insert: "" });
    } else {
      let spacesToRemove = 0;
      for (let i = 0; i < Math.min(indentUnit.length, text.length); i++) {
        if (text[i] === " ")
          spacesToRemove++;
        else
          break;
      }
      if (spacesToRemove > 0) {
        changes.push({ from: line.from, to: line.from + spacesToRemove, insert: "" });
      }
    }
  }
  if (changes.length > 0) {
    view.dispatch({
      changes,
      annotations: [blockEditorTransaction.of(true)]
    });
  }
}
function setHeadingLevel(view, selectedLines, level) {
  if (selectedLines.size === 0)
    return;
  const doc = view.state.doc;
  const changes = [];
  const sorted = Array.from(selectedLines).sort((a, b) => a - b);
  for (const lineNum of sorted) {
    if (lineNum < 1 || lineNum > doc.lines)
      continue;
    const line = doc.line(lineNum);
    const content = line.text.replace(/^#{1,6}\s+/, "");
    const prefix = level > 0 ? "#".repeat(level) + " " : "";
    const newText = prefix + content;
    if (newText !== line.text) {
      changes.push({ from: line.from, to: line.to, insert: newText });
    }
  }
  if (changes.length > 0) {
    view.dispatch({
      changes,
      annotations: [blockEditorTransaction.of(true)]
    });
  }
}
function toggleBulletList(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const doc = view.state.doc;
  const changes = [];
  const allBullets = Array.from(selectedLines).every((l) => isBulletItem(doc.line(l).text));
  for (const lineNum of selectedLines) {
    const line = doc.line(lineNum);
    const text = line.text;
    const ws = getLeadingWhitespace(text);
    if (allBullets) {
      const newText = text.replace(/^(\s*)([-*+])\s/, "$1");
      changes.push({ from: line.from, to: line.to, insert: newText });
    } else {
      let content = text.replace(/^(\s*)([-*+]|\d+\.)\s(\[[ x]\]\s)?/, "$1");
      changes.push({ from: line.from, to: line.to, insert: ws + "- " + content.trimStart() });
    }
  }
  view.dispatch({
    changes,
    annotations: [blockEditorTransaction.of(true)]
  });
}
function toggleNumberedList(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const doc = view.state.doc;
  const changes = [];
  const allNumbered = Array.from(selectedLines).every((l) => isNumberedItem(doc.line(l).text));
  let counter = 1;
  const sorted = Array.from(selectedLines).sort((a, b) => a - b);
  for (const lineNum of sorted) {
    const line = doc.line(lineNum);
    const text = line.text;
    const ws = getLeadingWhitespace(text);
    if (allNumbered) {
      const newText = text.replace(/^(\s*)\d+\.\s/, "$1");
      changes.push({ from: line.from, to: line.to, insert: newText });
    } else {
      let content = text.replace(/^(\s*)([-*+]|\d+\.)\s(\[[ x]\]\s)?/, "$1");
      changes.push({ from: line.from, to: line.to, insert: ws + counter + ". " + content.trimStart() });
      counter++;
    }
  }
  view.dispatch({
    changes,
    annotations: [blockEditorTransaction.of(true)]
  });
}
function toggleCheckbox(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const doc = view.state.doc;
  const changes = [];
  const allCheckbox = Array.from(selectedLines).every((l) => isCheckboxItem(doc.line(l).text));
  for (const lineNum of selectedLines) {
    const line = doc.line(lineNum);
    const text = line.text;
    const ws = getLeadingWhitespace(text);
    if (allCheckbox) {
      const newText = text.replace(/^(\s*)([-*+])\s\[[ x]\]\s/, "$1$2 ");
      changes.push({ from: line.from, to: line.to, insert: newText });
    } else {
      let content = text.replace(/^(\s*)([-*+]|\d+\.)\s(\[[ x]\]\s)?/, "$1");
      changes.push({ from: line.from, to: line.to, insert: ws + "- [ ] " + content.trimStart() });
    }
  }
  view.dispatch({
    changes,
    annotations: [blockEditorTransaction.of(true)]
  });
}
function deleteBlocks(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const expanded = expandWithChildren(view, selectedLines);
  const doc = view.state.doc;
  const changes = [];
  for (const lineNum of expanded) {
    const line = doc.line(lineNum);
    let from = line.from;
    let to = line.to;
    if (to < doc.length) {
      to += 1;
    } else if (from > 0) {
      from -= 1;
    }
    changes.push({ from, to, insert: "" });
  }
  view.dispatch({
    changes,
    effects: [setBlockSelection.of(/* @__PURE__ */ new Set())],
    annotations: [blockEditorTransaction.of(true)]
  });
}
function undoAction(view) {
  const commands = require("@codemirror/commands");
  commands.undo(view);
}
function redoAction(view) {
  const commands = require("@codemirror/commands");
  commands.redo(view);
}
function copyBlocks(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const expanded = expandWithChildren(view, selectedLines);
  const doc = view.state.doc;
  const lines = expanded.map((l) => doc.line(l).text);
  const text = lines.join("\n");
  navigator.clipboard.writeText(text);
}
function cutBlocks(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  copyBlocks(view, selectedLines);
  deleteBlocks(view, selectedLines);
}
function toggleQuote(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const doc = view.state.doc;
  const changes = [];
  const allQuoted = Array.from(selectedLines).every(
    (l) => doc.line(l).text.startsWith("> ")
  );
  for (const lineNum of selectedLines) {
    const line = doc.line(lineNum);
    const text = line.text;
    if (allQuoted) {
      changes.push({ from: line.from, to: line.to, insert: text.replace(/^> /, "") });
    } else {
      changes.push({ from: line.from, to: line.to, insert: "> " + text });
    }
  }
  view.dispatch({
    changes,
    annotations: [blockEditorTransaction.of(true)]
  });
}
function toggleInlineFormat(view, selectedLines, marker) {
  if (selectedLines.size === 0)
    return;
  const doc = view.state.doc;
  const changes = [];
  const sorted = Array.from(selectedLines).sort((a, b) => a - b);
  const allWrapped = sorted.every((ln) => {
    const text = doc.line(ln).text;
    const content = getContentPart(text);
    return content.startsWith(marker) && content.endsWith(marker) && content.length >= marker.length * 2;
  });
  for (const lineNum of sorted) {
    if (lineNum < 1 || lineNum > doc.lines)
      continue;
    const line = doc.line(lineNum);
    const text = line.text;
    const prefixEnd = getContentStartIndex(text);
    const prefix = text.slice(0, prefixEnd);
    const content = text.slice(prefixEnd);
    let newContent;
    if (allWrapped) {
      newContent = content.slice(marker.length, content.length - marker.length);
    } else {
      let stripped = content;
      if (stripped.startsWith(marker) && stripped.endsWith(marker) && stripped.length >= marker.length * 2) {
        stripped = stripped.slice(marker.length, stripped.length - marker.length);
      }
      newContent = marker + stripped + marker;
    }
    const newText = prefix + newContent;
    if (newText !== text) {
      changes.push({ from: line.from, to: line.to, insert: newText });
    }
  }
  if (changes.length > 0) {
    view.dispatch({
      changes,
      annotations: [blockEditorTransaction.of(true)]
    });
  }
}
function getContentPart(text) {
  return text.slice(getContentStartIndex(text));
}
function getContentStartIndex(text) {
  const wsMatch = text.match(/^(\s*)/);
  let idx = wsMatch ? wsMatch[1].length : 0;
  const rest = text.slice(idx);
  const headingMatch = rest.match(/^(#{1,6}\s+)/);
  if (headingMatch) {
    idx += headingMatch[1].length;
    return idx;
  }
  const listMatch = rest.match(/^((?:[-*+]|\d+\.)\s+(?:\[[ x]\]\s+)?)/);
  if (listMatch) {
    idx += listMatch[1].length;
    return idx;
  }
  const quoteMatch = rest.match(/^(>\s+)/);
  if (quoteMatch) {
    idx += quoteMatch[1].length;
    return idx;
  }
  return idx;
}
function toggleCodeFormat(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  toggleInlineFormat(view, selectedLines, "`");
}
function getFrontmatterEndForOps(view) {
  const doc = view.state.doc;
  if (doc.lines < 1)
    return 0;
  if (!/^---\s*$/.test(doc.line(1).text))
    return 0;
  for (let i = 2; i <= doc.lines; i++) {
    if (/^---\s*$/.test(doc.line(i).text))
      return i;
  }
  return 0;
}
function progressiveSelectAll(view, selectedLines) {
  const doc = view.state.doc;
  const frontmatterEnd = getFrontmatterEndForOps(view);
  const useTab = true;
  const tabSize = 4;
  if (selectedLines.size === 0) {
    const allLines2 = /* @__PURE__ */ new Set();
    for (let i = frontmatterEnd + 1; i <= doc.lines; i++) {
      if (doc.line(i).text.trim() !== "")
        allLines2.add(i);
    }
    view.dispatch({ effects: [setBlockSelection.of(allLines2)] });
    return;
  }
  const sorted = Array.from(selectedLines).sort((a, b) => a - b);
  let minIndent = Infinity;
  for (const ln of sorted) {
    const indent = getIndentLevel(doc.line(ln).text, tabSize, useTab);
    if (indent < minIndent)
      minIndent = indent;
  }
  if (minIndent > 0) {
    let parentLine = -1;
    for (let i = sorted[0] - 1; i > frontmatterEnd; i--) {
      const text = doc.line(i).text;
      if (text.trim() === "")
        continue;
      const indent = getIndentLevel(text, tabSize, useTab);
      if (indent < minIndent) {
        parentLine = i;
        break;
      }
    }
    if (parentLine !== -1) {
      const [scopeStart, scopeEnd] = getBlockWithChildren(view.state, parentLine, tabSize, useTab);
      let allSiblingsSelected = true;
      for (let i = scopeStart; i <= scopeEnd; i++) {
        const text = doc.line(i).text;
        if (text.trim() === "")
          continue;
        const indent = getIndentLevel(text, tabSize, useTab);
        if (indent === minIndent && !selectedLines.has(i)) {
          allSiblingsSelected = false;
          break;
        }
      }
      if (!allSiblingsSelected) {
        const newSelection = /* @__PURE__ */ new Set();
        for (let i = scopeStart; i <= scopeEnd; i++) {
          const text = doc.line(i).text;
          if (text.trim() === "")
            continue;
          if (getIndentLevel(text, tabSize, useTab) >= minIndent) {
            newSelection.add(i);
          }
        }
        view.dispatch({ effects: [setBlockSelection.of(newSelection)] });
        return;
      } else {
        const newSelection = /* @__PURE__ */ new Set();
        for (let i = scopeStart; i <= scopeEnd; i++) {
          if (doc.line(i).text.trim() !== "")
            newSelection.add(i);
        }
        view.dispatch({ effects: [setBlockSelection.of(newSelection)] });
        return;
      }
    }
  }
  const isListContent = (text) => {
    return isBulletItem(text) || isNumberedItem(text) || isCheckboxItem(text) || getIndentLevel(text, tabSize, useTab) > 0;
  };
  let regionStart = sorted[0];
  for (let i = sorted[0] - 1; i > frontmatterEnd; i--) {
    const text = doc.line(i).text;
    if (text.trim() === "")
      break;
    if (!isListContent(text) && !selectedLines.has(i))
      break;
    regionStart = i;
  }
  const [, lastChildEnd] = getBlockWithChildren(view.state, sorted[sorted.length - 1], tabSize, useTab);
  let regionEnd = Math.max(sorted[sorted.length - 1], lastChildEnd);
  for (let i = regionEnd + 1; i <= doc.lines; i++) {
    const text = doc.line(i).text;
    if (text.trim() === "")
      break;
    if (!isListContent(text))
      break;
    regionEnd = i;
  }
  const regionSelection = /* @__PURE__ */ new Set();
  for (let i = regionStart; i <= regionEnd; i++) {
    if (doc.line(i).text.trim() !== "")
      regionSelection.add(i);
  }
  if (regionSelection.size > selectedLines.size) {
    view.dispatch({ effects: [setBlockSelection.of(regionSelection)] });
    return;
  }
  const allLines = /* @__PURE__ */ new Set();
  for (let i = frontmatterEnd + 1; i <= doc.lines; i++) {
    if (doc.line(i).text.trim() !== "")
      allLines.add(i);
  }
  view.dispatch({ effects: [setBlockSelection.of(allLines)] });
}

// src/gutter.ts
var gutterExitCooldownUntil = 0;
function setExitCooldown(_view, until) {
  gutterExitCooldownUntil = until;
}
var dragSelectActive = false;
function isDragSelecting() {
  return dragSelectActive;
}
function getFrontmatterEnd(view) {
  const doc = view.state.doc;
  if (doc.lines < 1)
    return 0;
  if (doc.line(1).text.trim() !== "---")
    return 0;
  for (let i = 2; i <= doc.lines; i++) {
    if (doc.line(i).text.trim() === "---")
      return i;
  }
  return 0;
}
var blockModeTransactionFilter = import_state4.EditorState.transactionFilter.of((tr) => {
  const state = tr.startState.field(blockSelectionState);
  if (!state.active)
    return tr;
  if (tr.annotation(blockEditorTransaction))
    return tr;
  if (tr.effects.length > 0)
    return tr;
  if (tr.docChanged) {
    const userEvent = tr.annotation(import_state4.Transaction.userEvent);
    if (userEvent)
      return [];
    return tr;
  }
  return tr;
});
var blockSelectionGutter = import_view.ViewPlugin.fromClass(
  class {
    constructor(view) {
      this.view = view;
      this.pointerStart = null;
      // Long-press to enter block mode
      this.longPressTimer = null;
      this.longPressStart = null;
      // Drag-select across circles
      this.circlePositions = [];
      this.dragAnchorLine = null;
      this.dragSelectionBefore = /* @__PURE__ */ new Set();
      this.dragIsDeselecting = false;
      this.dragLastLine = null;
      // Auto-scroll during drag
      this.autoScrollRAF = null;
      this.autoScrollSpeed = 0;
      this.lastDragClientY = 0;
      this.container = document.createElement("div");
      this.container.className = "block-editor-gutter";
      this.container.style.display = "none";
      document.body.appendChild(this.container);
      this.scrollHandler = () => {
        if (this.view.state.field(blockSelectionState).active) {
          this.buildGutter();
        }
      };
      view.scrollDOM.addEventListener("scroll", this.scrollHandler);
      this.focusHandler = () => {
        if (this.view.state.field(blockSelectionState).active || Date.now() < gutterExitCooldownUntil) {
          setTimeout(() => this.view.contentDOM.blur(), 0);
        }
      };
      view.contentDOM.addEventListener("focus", this.focusHandler);
      this.contentPointerDownHandler = (e) => {
        if (!this.view.state.field(blockSelectionState).active)
          return;
        if (e.target.closest(".block-editor-gutter-circle"))
          return;
        this.pointerStart = { x: e.clientX, y: e.clientY };
      };
      this.contentPointerUpHandler = (e) => {
        if (!this.pointerStart)
          return;
        if (!this.view.state.field(blockSelectionState).active) {
          this.pointerStart = null;
          return;
        }
        const dx = e.clientX - this.pointerStart.x;
        const dy = e.clientY - this.pointerStart.y;
        this.pointerStart = null;
        if (Math.sqrt(dx * dx + dy * dy) > 10)
          return;
        const pos = this.view.posAtCoords({ x: e.clientX, y: e.clientY });
        if (pos === null)
          return;
        const lineNum = this.view.state.doc.lineAt(pos).number;
        const frontmatterEnd = getFrontmatterEnd(this.view);
        if (lineNum <= frontmatterEnd)
          return;
        e.preventDefault();
        this.toggleLineWithChildren(lineNum);
      };
      view.contentDOM.addEventListener("pointerdown", this.contentPointerDownHandler);
      view.contentDOM.addEventListener("pointerup", this.contentPointerUpHandler);
      this.touchStartHandler = (e) => {
        if (this.view.state.field(blockSelectionState).active)
          return;
        if (this.view.hasFocus)
          return;
        const touch = e.touches[0];
        this.longPressStart = { x: touch.clientX, y: touch.clientY };
        this.view.contentDOM.style.userSelect = "none";
        this.view.contentDOM.style.webkitUserSelect = "none";
        this.view.contentDOM.style.webkitTouchCallout = "none";
        this.longPressTimer = setTimeout(() => {
          this.longPressTimer = null;
          if (!this.longPressStart)
            return;
          const pos = this.view.posAtCoords(this.longPressStart);
          if (pos === null) {
            this.clearLongPress();
            return;
          }
          const lineNum = this.view.state.doc.lineAt(pos).number;
          const frontmatterEnd = getFrontmatterEnd(this.view);
          if (lineNum <= frontmatterEnd) {
            this.clearLongPress();
            return;
          }
          const [start, end] = getBlockWithChildren(this.view.state, lineNum, 4, true);
          const selected = /* @__PURE__ */ new Set();
          for (let i = start; i <= end; i++) {
            if (this.view.state.doc.line(i).text.trim() !== "") {
              selected.add(i);
            }
          }
          this.view.dispatch({
            effects: [toggleBlockMode.of(true), setBlockSelection.of(selected)]
          });
          const winSel = window.getSelection();
          if (winSel)
            winSel.removeAllRanges();
          this.view.contentDOM.blur();
          this.clearLongPress();
        }, 800);
      };
      this.touchMoveHandler = (e) => {
        if (!this.longPressStart || !this.longPressTimer)
          return;
        const touch = e.touches[0];
        const dx = touch.clientX - this.longPressStart.x;
        const dy = touch.clientY - this.longPressStart.y;
        if (Math.sqrt(dx * dx + dy * dy) > 10) {
          this.cancelLongPress();
        }
      };
      this.touchEndHandler = () => {
        this.cancelLongPress();
      };
      view.contentDOM.addEventListener("touchstart", this.touchStartHandler, { passive: true });
      view.contentDOM.addEventListener("touchmove", this.touchMoveHandler, { passive: true });
      view.contentDOM.addEventListener("touchend", this.touchEndHandler);
      view.contentDOM.addEventListener("touchcancel", this.touchEndHandler);
      this.dragMoveHandler = (e) => {
        if (this.dragAnchorLine === null)
          return;
        this.lastDragClientY = e.clientY;
        if (!dragSelectActive)
          dragSelectActive = true;
        this.updateDragSelection(e.clientY);
        this.updateAutoScroll(e.clientY);
      };
      this.dragEndHandler = () => {
        this.stopAutoScroll();
        this.dragAnchorLine = null;
        this.dragLastLine = null;
        dragSelectActive = false;
      };
      document.addEventListener("pointermove", this.dragMoveHandler);
      document.addEventListener("pointerup", this.dragEndHandler);
      document.addEventListener("pointercancel", this.dragEndHandler);
    }
    update(update) {
      const state = update.state.field(blockSelectionState);
      const prev = update.startState.field(blockSelectionState);
      if (state.active && !prev.active) {
        this.view.contentDOM.blur();
      }
      if (state.active !== prev.active || state.selectedBlocks !== prev.selectedBlocks || update.docChanged || update.viewportChanged || update.geometryChanged) {
        this.buildGutter();
      }
    }
    /**
     * Toggle selection for a line and its children.
     * Selecting a parent auto-selects all indented children below it.
     * If the parent+children are already all selected, deselect them all.
     */
    clearLongPress() {
      this.longPressStart = null;
      this.view.contentDOM.style.userSelect = "";
      this.view.contentDOM.style.webkitUserSelect = "";
      this.view.contentDOM.style.webkitTouchCallout = "";
    }
    cancelLongPress() {
      if (this.longPressTimer) {
        clearTimeout(this.longPressTimer);
        this.longPressTimer = null;
      }
      this.clearLongPress();
    }
    /**
     * Find the nearest circle line number for a given screen Y position.
     */
    findNearestCircleLine(y) {
      let best = null;
      let bestDist = Infinity;
      for (const cp of this.circlePositions) {
        const dist = Math.abs(y - cp.centerY);
        if (dist < bestDist) {
          bestDist = dist;
          best = cp.lineNum;
        }
      }
      const maxDist = this.autoScrollSpeed !== 0 ? 200 : 40;
      return bestDist < maxDist ? best : null;
    }
    /**
     * Update selection based on current drag Y position.
     */
    updateDragSelection(clientY) {
      this.rebuildCirclePositions();
      const lineNum = this.findNearestCircleLine(clientY);
      if (lineNum === null || lineNum === this.dragLastLine)
        return;
      this.dragLastLine = lineNum;
      const newSet = new Set(this.dragSelectionBefore);
      const lo = Math.min(this.dragAnchorLine, lineNum);
      const hi = Math.max(this.dragAnchorLine, lineNum);
      const doc = this.view.state.doc;
      const dragLines = /* @__PURE__ */ new Set();
      for (let ln = lo; ln <= hi; ln++) {
        const [start, end] = getBlockWithChildren(this.view.state, ln, 4, true);
        for (let i = start; i <= end; i++) {
          if (i >= 1 && i <= doc.lines && doc.line(i).text.trim() !== "") {
            dragLines.add(i);
          }
        }
      }
      if (this.dragIsDeselecting) {
        for (const ln of dragLines) {
          newSet.delete(ln);
        }
      } else {
        for (const ln of dragLines) {
          newSet.add(ln);
        }
      }
      if (navigator.vibrate)
        navigator.vibrate(5);
      this.view.dispatch({
        effects: [setBlockSelection.of(newSet)]
      });
    }
    /**
     * Rebuild circle positions from current scroll state (without clearing DOM).
     */
    rebuildCirclePositions() {
      const frontmatterEnd = getFrontmatterEnd(this.view);
      const doc = this.view.state.doc;
      const contentTop = this.view.contentDOM.getBoundingClientRect().top;
      const scrollerRect = this.view.scrollDOM.getBoundingClientRect();
      this.circlePositions = [];
      const { from, to } = this.view.viewport;
      const startLine = doc.lineAt(from).number;
      const endLine = doc.lineAt(to).number;
      for (let lineNum = startLine; lineNum <= endLine; lineNum++) {
        if (lineNum <= frontmatterEnd)
          continue;
        const line = doc.line(lineNum);
        if (line.text.trim() === "")
          continue;
        const block = this.view.lineBlockAt(line.from);
        const screenY = contentTop + block.top;
        if (screenY + block.height < scrollerRect.top)
          continue;
        if (screenY > scrollerRect.bottom)
          continue;
        const circleTop = screenY + (block.height - 28) / 2;
        this.circlePositions.push({ lineNum, centerY: circleTop + 14 });
      }
    }
    /**
     * Start or update auto-scrolling based on pointer proximity to edges.
     */
    updateAutoScroll(clientY) {
      const scrollerRect = this.view.scrollDOM.getBoundingClientRect();
      const edgeZone = 150;
      const maxSpeed = 30;
      if (clientY < scrollerRect.top + edgeZone) {
        const proximity = (scrollerRect.top + edgeZone - clientY) / edgeZone;
        this.autoScrollSpeed = -maxSpeed * Math.min(proximity, 1);
      } else if (clientY > scrollerRect.bottom - edgeZone) {
        const proximity = (clientY - (scrollerRect.bottom - edgeZone)) / edgeZone;
        this.autoScrollSpeed = maxSpeed * Math.min(proximity, 1);
      } else {
        this.stopAutoScroll();
        return;
      }
      if (this.autoScrollRAF === null) {
        this.autoScrollLoop();
      }
    }
    autoScrollLoop() {
      if (this.dragAnchorLine === null || this.autoScrollSpeed === 0) {
        this.stopAutoScroll();
        return;
      }
      this.view.scrollDOM.scrollTop += this.autoScrollSpeed;
      this.buildGutter();
      this.updateDragSelection(this.lastDragClientY);
      this.autoScrollRAF = requestAnimationFrame(() => this.autoScrollLoop());
    }
    stopAutoScroll() {
      this.autoScrollSpeed = 0;
      if (this.autoScrollRAF !== null) {
        cancelAnimationFrame(this.autoScrollRAF);
        this.autoScrollRAF = null;
      }
    }
    /**
     * Start drag-select from a circle. Called BEFORE toggleLineWithChildren
     * so we can check if the line was already selected (deselect mode) or not.
     */
    startDragSelect(lineNum) {
      const state = this.view.state.field(blockSelectionState);
      this.dragIsDeselecting = state.selectedBlocks.has(lineNum);
      this.dragSelectionBefore = new Set(state.selectedBlocks);
      this.dragAnchorLine = lineNum;
      this.dragLastLine = lineNum;
    }
    toggleLineWithChildren(lineNum) {
      const state = this.view.state.field(blockSelectionState);
      const [start, end] = getBlockWithChildren(this.view.state, lineNum, 4, true);
      const newSet = new Set(state.selectedBlocks);
      let allSelected = true;
      for (let i = start; i <= end; i++) {
        const lineText = this.view.state.doc.line(i).text;
        if (lineText.trim() === "")
          continue;
        if (!newSet.has(i)) {
          allSelected = false;
          break;
        }
      }
      if (allSelected) {
        for (let i = start; i <= end; i++) {
          newSet.delete(i);
        }
      } else {
        for (let i = start; i <= end; i++) {
          const lineText = this.view.state.doc.line(i).text;
          if (lineText.trim() === "")
            continue;
          newSet.add(i);
        }
      }
      if (navigator.vibrate) {
        navigator.vibrate(5);
      }
      this.view.dispatch({
        effects: [setBlockSelection.of(newSet)]
      });
    }
    buildGutter() {
      const state = this.view.state.field(blockSelectionState);
      this.container.innerHTML = "";
      if (!state.active) {
        this.container.style.display = "none";
        return;
      }
      this.container.style.display = "block";
      const frontmatterEnd = getFrontmatterEnd(this.view);
      const { from, to } = this.view.viewport;
      const doc = this.view.state.doc;
      const startLine = doc.lineAt(from).number;
      const endLine = doc.lineAt(to).number;
      const contentTop = this.view.contentDOM.getBoundingClientRect().top;
      const scrollerRect = this.view.scrollDOM.getBoundingClientRect();
      const circleLeft = scrollerRect.right - 44;
      this.circlePositions = [];
      for (let lineNum = startLine; lineNum <= endLine; lineNum++) {
        if (lineNum <= frontmatterEnd)
          continue;
        const line = doc.line(lineNum);
        if (line.text.trim() === "")
          continue;
        const block = this.view.lineBlockAt(line.from);
        const screenY = contentTop + block.top;
        if (screenY + block.height < scrollerRect.top)
          continue;
        if (screenY > scrollerRect.bottom)
          continue;
        const circle = document.createElement("div");
        circle.className = "block-editor-gutter-circle";
        if (state.selectedBlocks.has(lineNum)) {
          circle.classList.add("selected");
        }
        const circleTop = screenY + (block.height - 28) / 2;
        circle.style.top = circleTop + "px";
        circle.style.left = circleLeft + "px";
        this.circlePositions.push({ lineNum, centerY: circleTop + 14 });
        circle.addEventListener("pointerdown", (e) => {
          e.preventDefault();
          e.stopPropagation();
          this.startDragSelect(lineNum);
          this.toggleLineWithChildren(lineNum);
        });
        circle.addEventListener("mousedown", (e) => {
          e.preventDefault();
          e.stopPropagation();
        });
        circle.addEventListener("touchstart", (e) => {
          e.preventDefault();
          e.stopPropagation();
        }, { passive: false });
        this.container.appendChild(circle);
      }
    }
    destroy() {
      this.cancelLongPress();
      this.stopAutoScroll();
      this.dragAnchorLine = null;
      this.container.remove();
      this.view.scrollDOM.removeEventListener("scroll", this.scrollHandler);
      this.view.contentDOM.removeEventListener("focus", this.focusHandler);
      this.view.contentDOM.removeEventListener("pointerdown", this.contentPointerDownHandler);
      this.view.contentDOM.removeEventListener("pointerup", this.contentPointerUpHandler);
      this.view.contentDOM.removeEventListener("touchstart", this.touchStartHandler);
      this.view.contentDOM.removeEventListener("touchmove", this.touchMoveHandler);
      this.view.contentDOM.removeEventListener("touchend", this.touchEndHandler);
      this.view.contentDOM.removeEventListener("touchcancel", this.touchEndHandler);
      document.removeEventListener("pointermove", this.dragMoveHandler);
      document.removeEventListener("pointerup", this.dragEndHandler);
      document.removeEventListener("pointercancel", this.dragEndHandler);
    }
  }
);

// src/highlighter.ts
var import_view2 = require("@codemirror/view");
var import_state6 = require("@codemirror/state");
var blockHighlighter = import_view2.ViewPlugin.fromClass(
  class {
    constructor(view) {
      this.view = view;
      this.decorations = this.buildDecorations();
    }
    update(update) {
      const state = update.state.field(blockSelectionState);
      const prevState = update.startState.field(blockSelectionState);
      if (state.active !== prevState.active || state.selectedBlocks !== prevState.selectedBlocks || update.docChanged || update.viewportChanged) {
        this.decorations = this.buildDecorations();
      }
    }
    buildDecorations() {
      const state = this.view.state.field(blockSelectionState);
      if (!state.active || state.selectedBlocks.size === 0) {
        return import_view2.Decoration.none;
      }
      const builder = new import_state6.RangeSetBuilder();
      const lineDeco = import_view2.Decoration.line({ class: "block-editor-selected-line" });
      const sorted = Array.from(state.selectedBlocks).sort((a, b) => a - b);
      const doc = this.view.state.doc;
      for (const lineNum of sorted) {
        if (lineNum >= 1 && lineNum <= doc.lines) {
          const line = doc.line(lineNum);
          builder.add(line.from, line.from, lineDeco);
        }
      }
      return builder.finish();
    }
  },
  {
    decorations: (v) => v.decorations
  }
);

// src/toolbar.ts
var import_obsidian = require("obsidian");
var BlockEditorToolbar = class {
  constructor(indentUnit) {
    this.view = null;
    this.showingFormat = false;
    this.indentUnit = indentUnit;
    this.el = document.createElement("div");
    this.el.className = "block-editor-toolbar";
    this.el.style.display = "none";
    this.primaryPill = this.buildPrimaryPill();
    this.formatPopup = this.buildFormatPopup();
    this.el.appendChild(this.primaryPill);
    this.el.appendChild(this.formatPopup);
    this.el.addEventListener("pointerdown", (e) => e.preventDefault());
  }
  setView(view) {
    this.view = view;
  }
  setIndentUnit(unit) {
    this.indentUnit = unit;
  }
  buildPrimaryPill() {
    const pill = document.createElement("div");
    pill.className = "block-editor-pill";
    const items = [
      { icon: "case-sensitive", title: "Format", action: () => this.toggleFormatPopup() },
      "separator",
      { icon: "undo-2", title: "Undo", action: () => this.doUndo() },
      { icon: "redo-2", title: "Redo", action: () => this.doRedo() },
      { icon: "arrow-up", title: "Move Up", action: () => this.doAction(moveBlocksUp) },
      { icon: "arrow-down", title: "Move Down", action: () => this.doAction(moveBlocksDown) },
      { icon: "check-check", title: "Select All", action: () => this.doSelectAll() },
      { icon: "scissors", title: "Cut", action: () => this.doCut() },
      { icon: "copy", title: "Copy", action: () => this.doCopy() },
      "separator",
      { icon: "trash-2", title: "Delete", action: () => this.doDelete(), className: "block-editor-btn-danger" }
    ];
    for (const item of items) {
      if (item === "separator") {
        const sep = document.createElement("div");
        sep.className = "block-editor-pill-separator";
        pill.appendChild(sep);
      } else {
        const el = this.makeButton(item.icon, item.title, item.action, item.className);
        pill.appendChild(el);
      }
    }
    return pill;
  }
  buildFormatPopup() {
    const popup = document.createElement("div");
    popup.className = "block-editor-format-popup";
    popup.style.display = "none";
    const header = document.createElement("div");
    header.className = "block-editor-format-header";
    const label = document.createElement("span");
    label.className = "block-editor-format-label";
    label.textContent = "Format";
    header.appendChild(label);
    const closeBtn = document.createElement("button");
    closeBtn.className = "block-editor-format-close";
    closeBtn.setAttribute("aria-label", "Close");
    (0, import_obsidian.setIcon)(closeBtn, "x");
    closeBtn.addEventListener("pointerup", (e) => {
      e.preventDefault();
      e.stopPropagation();
      this.toggleFormatPopup();
    });
    header.appendChild(closeBtn);
    popup.appendChild(header);
    const headingRow = document.createElement("div");
    headingRow.className = "block-editor-format-headings";
    const headings = [
      { label: "Title", level: 1 },
      { label: "Subtitle", level: 2 },
      { label: "Heading", level: 3 },
      { label: "Strong", level: 4 },
      { label: "Body", level: 0 }
    ];
    for (const h of headings) {
      const btn = document.createElement("button");
      btn.className = `block-editor-heading-btn block-editor-heading-${h.level}`;
      btn.textContent = h.label;
      let downPos = null;
      btn.addEventListener("pointerdown", (e) => {
        e.preventDefault();
        e.stopPropagation();
        downPos = { x: e.clientX, y: e.clientY };
      });
      btn.addEventListener("pointerup", (e) => {
        if (!downPos)
          return;
        const dx = e.clientX - downPos.x;
        const dy = e.clientY - downPos.y;
        downPos = null;
        if (Math.sqrt(dx * dx + dy * dy) > 10)
          return;
        e.preventDefault();
        e.stopPropagation();
        const selected = this.getSelectedLines();
        if (selected && this.view) {
          setHeadingLevel(this.view, selected, h.level);
        }
      });
      btn.addEventListener("pointercancel", () => {
        downPos = null;
      });
      headingRow.appendChild(btn);
    }
    popup.appendChild(headingRow);
    const listRow = document.createElement("div");
    listRow.className = "block-editor-format-row";
    const listPill = document.createElement("div");
    listPill.className = "block-editor-format-pill";
    const listButtons = [
      { icon: "list", title: "Bullet List", action: () => this.doAction(toggleBulletList) },
      { icon: "list-ordered", title: "Numbered List", action: () => this.doAction(toggleNumberedList) },
      { icon: "check-square", title: "Checklist", action: () => this.doAction(toggleCheckbox) },
      { icon: "text-quote", title: "Quote", action: () => this.doAction(toggleQuote) },
      { icon: "code", title: "Code", action: () => this.doCodeFormat() }
    ];
    for (const btn of listButtons) {
      listPill.appendChild(this.makeButton(btn.icon, btn.title, btn.action));
    }
    listRow.appendChild(listPill);
    popup.appendChild(listRow);
    const inlineRow = document.createElement("div");
    inlineRow.className = "block-editor-format-row";
    const inlinePill = document.createElement("div");
    inlinePill.className = "block-editor-format-pill";
    const inlineButtons = [
      { icon: "bold", title: "Bold", action: () => this.doInlineFormat("**") },
      { icon: "italic", title: "Italic", action: () => this.doInlineFormat("*") },
      { icon: "strikethrough", title: "Strikethrough", action: () => this.doInlineFormat("~~") },
      { icon: "highlighter", title: "Highlight", action: () => this.doInlineFormat("==") }
    ];
    for (const btn of inlineButtons) {
      inlinePill.appendChild(this.makeButton(btn.icon, btn.title, btn.action));
    }
    inlineRow.appendChild(inlinePill);
    const indentPill = document.createElement("div");
    indentPill.className = "block-editor-format-pill";
    const indentButtons = [
      { icon: "outdent", title: "Outdent", action: () => this.doOutdent() },
      { icon: "indent", title: "Indent", action: () => this.doIndent() }
    ];
    for (const btn of indentButtons) {
      indentPill.appendChild(this.makeButton(btn.icon, btn.title, btn.action));
    }
    inlineRow.appendChild(indentPill);
    popup.appendChild(inlineRow);
    return popup;
  }
  makeButton(icon, title, action, className) {
    const btn = document.createElement("button");
    btn.setAttribute("aria-label", title);
    btn.title = title;
    if (className)
      btn.classList.add(className);
    (0, import_obsidian.setIcon)(btn, icon);
    let downPos = null;
    btn.addEventListener("pointerdown", (e) => {
      e.preventDefault();
      e.stopPropagation();
      downPos = { x: e.clientX, y: e.clientY };
    });
    btn.addEventListener("pointerup", (e) => {
      if (!downPos)
        return;
      const dx = e.clientX - downPos.x;
      const dy = e.clientY - downPos.y;
      downPos = null;
      if (Math.sqrt(dx * dx + dy * dy) > 10)
        return;
      e.preventDefault();
      e.stopPropagation();
      action();
    });
    btn.addEventListener("pointercancel", () => {
      downPos = null;
    });
    return btn;
  }
  toggleFormatPopup() {
    this.showingFormat = !this.showingFormat;
    if (this.showingFormat) {
      this.primaryPill.style.display = "none";
      this.formatPopup.style.display = "flex";
    } else {
      this.primaryPill.style.display = "flex";
      this.formatPopup.style.display = "none";
    }
  }
  getSelectedLines() {
    if (!this.view)
      return null;
    const state = this.view.state.field(blockSelectionState);
    if (!state.active || state.selectedBlocks.size === 0)
      return null;
    return state.selectedBlocks;
  }
  doAction(fn) {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    fn(this.view, selected);
  }
  doIndent() {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    indentBlocks(this.view, selected, this.indentUnit);
  }
  doOutdent() {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    outdentBlocks(this.view, selected, this.indentUnit);
  }
  doDelete() {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    deleteBlocks(this.view, selected);
  }
  doCopy() {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    copyBlocks(this.view, selected);
  }
  doCut() {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    cutBlocks(this.view, selected);
  }
  doSelectAll() {
    if (!this.view)
      return;
    const state = this.view.state.field(blockSelectionState);
    progressiveSelectAll(this.view, state.selectedBlocks);
  }
  doInlineFormat(marker) {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    toggleInlineFormat(this.view, selected, marker);
  }
  doCodeFormat() {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    toggleCodeFormat(this.view, selected);
  }
  doUndo() {
    if (!this.view)
      return;
    undoAction(this.view);
  }
  doRedo() {
    if (!this.view)
      return;
    redoAction(this.view);
  }
  show() {
    this.el.style.display = "flex";
    if (this.showingFormat) {
      this.primaryPill.style.display = "none";
      this.formatPopup.style.display = "flex";
    } else {
      this.primaryPill.style.display = "flex";
      this.formatPopup.style.display = "none";
    }
  }
  hide() {
    this.el.style.display = "none";
    this.showingFormat = false;
    this.primaryPill.style.display = "flex";
    this.formatPopup.style.display = "none";
  }
  destroy() {
    this.el.remove();
  }
  updateVisibility(active, hasSelection) {
    if (active && hasSelection) {
      this.show();
    } else {
      this.hide();
    }
  }
};

// src/fab.ts
var import_obsidian2 = require("obsidian");
var BlockEditorFAB = class {
  constructor() {
    this.view = null;
    this.el = document.createElement("button");
    this.el.className = "block-editor-fab";
    this.el.style.display = "none";
    this.el.setAttribute("aria-label", "Exit Block Mode");
    (0, import_obsidian2.setIcon)(this.el, "x");
    this.el.addEventListener("pointerdown", (e) => {
      e.preventDefault();
      e.stopPropagation();
      this.exitBlockMode();
    });
    this.el.addEventListener("mousedown", (e) => e.preventDefault());
    this.el.addEventListener("touchstart", (e) => e.preventDefault(), { passive: false });
  }
  setView(view) {
    this.view = view;
  }
  exitBlockMode() {
    if (!this.view)
      return;
    this.view.dispatch({
      effects: [toggleBlockMode.of(false)]
    });
  }
  updateAppearance(active) {
    if (active) {
      this.el.classList.add("active");
    } else {
      this.el.classList.remove("active");
    }
  }
  destroy() {
    this.el.remove();
  }
};

// src/styles.ts
function injectStyles() {
  const style = document.createElement("style");
  style.id = "block-editor-styles";
  style.textContent = `
/* Gutter: invisible wrapper on document.body */
.block-editor-gutter {
	position: fixed;
	top: 0;
	left: 0;
	width: 0;
	height: 0;
	z-index: 5;
	pointer-events: none;
}

/* Each circle is position:fixed with its own top/left.
   The element is wider than the visual circle for a bigger tap target. */
.block-editor-gutter-circle {
	position: fixed;
	width: 44px;
	height: 28px;
	cursor: pointer;
	pointer-events: auto;
	z-index: 5;
	background: transparent;
	border: none;
	box-sizing: border-box;
	display: flex;
	align-items: center;
	justify-content: flex-start;
}

.block-editor-gutter-circle::before {
	content: "";
	width: 20px;
	height: 20px;
	border-radius: 50%;
	border: 2px solid var(--interactive-accent);
	background: var(--background-primary);
	transition: background-color 0.15s ease, transform 0.1s ease;
	box-sizing: border-box;
	flex-shrink: 0;
}

.block-editor-gutter-circle:active::before {
	transform: scale(0.9);
}

.block-editor-gutter-circle.selected::before {
	background: var(--interactive-accent);
}

/* Line highlight decoration */
.cm-line.block-editor-selected-line {
	background-color: rgba(72, 120, 208, 0.15) !important;
}

/* Toolbar container \u2014 floats above content, positioned to replace Obsidian's bottom bar */
.block-editor-toolbar {
	position: fixed;
	bottom: 0;
	left: 0;
	right: 0;
	display: flex;
	flex-direction: column;
	align-items: center;
	z-index: 100;
	pointer-events: none;
}

/* Hide Obsidian's native bottom toolbar when block editor toolbar is visible */
body.block-editor-active .workspace-drawer.mod-left,
body.block-editor-active .mobile-toolbar,
body.block-editor-active .workspace-tab-header-container {
	display: none !important;
}

/* Primary pill \u2014 85% width on mobile, max-width on larger screens */
.block-editor-pill {
	display: flex;
	align-items: center;
	justify-content: space-evenly;
	width: 85%;
	max-width: 500px;
	padding: 4px 10px;
	margin-bottom: calc(env(safe-area-inset-bottom, 0px));
	border-radius: 100px;
	background: var(--background-secondary);
	border: 1px solid var(--background-modifier-border);
	pointer-events: auto;
	overflow-x: auto;
	-webkit-overflow-scrolling: touch;
	scrollbar-width: none;
}

.block-editor-pill::-webkit-scrollbar {
	display: none;
}

/* Vertical separator inside pill */
.block-editor-pill-separator {
	width: 1px;
	height: 28px;
	background: var(--text-faint);
	opacity: 0.3;
	flex-shrink: 0;
	margin: 0 4px;
}

/* All buttons inside toolbar \u2014 borderless, no background, icon-only */
.block-editor-toolbar button {
	display: flex;
	align-items: center;
	justify-content: center;
	min-width: 44px;
	height: 44px;
	border: none !important;
	outline: none !important;
	border-radius: 10px;
	background: transparent !important;
	box-shadow: none !important;
	color: var(--text-normal);
	cursor: pointer;
	padding: 0;
	touch-action: manipulation;
	flex-shrink: 0;
	-webkit-appearance: none;
	appearance: none;
}

.block-editor-toolbar button:active {
	background: var(--background-modifier-hover) !important;
}

.block-editor-toolbar button.block-editor-btn-danger {
	color: var(--text-error);
}

.block-editor-toolbar button.block-editor-btn-danger:active {
	background: rgba(255, 59, 48, 0.12) !important;
}

/* Default icon size for format popup buttons */
.block-editor-toolbar button .svg-icon {
	width: 20px;
	height: 20px;
	color: inherit;
	stroke: currentColor;
}

/* Icons in primary pill \u2014 larger, must come after default to override */
.block-editor-pill button .svg-icon {
	width: 26px;
	height: 26px;
}

/* Format popup \u2014 concentric with screen corners.
   Corner radius 40px, equal inset from bottom, left, and right edges. */
.block-editor-format-popup {
	display: flex;
	flex-direction: column;
	gap: 10px;
	padding: 16px 16px 18px;
	border-radius: 40px;
	background: var(--background-secondary);
	border: 1px solid var(--background-modifier-border);
	width: calc(100% - 16px);
	max-width: 500px;
	margin-bottom: env(safe-area-inset-bottom, 0px);
	pointer-events: auto;
}

/* Format popup header */
.block-editor-format-header {
	display: flex;
	align-items: center;
	justify-content: space-between;
	padding: 0 6px 0;
}

.block-editor-format-label {
	font-size: 20px;
	font-weight: 700;
	color: var(--text-normal);
}

.block-editor-format-close {
	min-width: 36px !important;
	height: 36px !important;
	border-radius: 50% !important;
}

.block-editor-format-close .svg-icon {
	width: 20px !important;
	height: 20px !important;
}

/* Heading row \u2014 plain text buttons, horizontally scrollable */
.block-editor-format-headings {
	display: flex;
	gap: 0;
	overflow-x: auto;
	-webkit-overflow-scrolling: touch;
	scrollbar-width: none;
	padding: 0 4px;
}

.block-editor-format-headings::-webkit-scrollbar {
	display: none;
}

.block-editor-heading-btn {
	display: flex;
	align-items: center;
	justify-content: flex-start;
	border: none !important;
	outline: none !important;
	background: transparent !important;
	box-shadow: none !important;
	cursor: pointer;
	padding: 8px 12px !important;
	border-radius: 8px !important;
	color: var(--text-normal);
	white-space: nowrap;
	touch-action: manipulation;
	flex-shrink: 0;
	font-family: var(--font-text);
	height: auto !important;
	min-height: 40px;
	-webkit-appearance: none;
	appearance: none;
}

.block-editor-heading-btn:active {
	background: var(--background-modifier-hover) !important;
}

/* Heading sizes \u2014 progressively smaller to show hierarchy */
.block-editor-heading-1 {
	font-size: 24px;
	font-weight: 700;
}

.block-editor-heading-2 {
	font-size: 19px;
	font-weight: 700;
}

.block-editor-heading-3 {
	font-size: 16px;
	font-weight: 600;
}

.block-editor-heading-4 {
	font-size: 14px;
	font-weight: 400;
}

.block-editor-heading-0 {
	font-size: 14px;
	font-weight: 400;
	color: var(--text-muted);
}

/* Format rows */
.block-editor-format-row {
	display: flex;
	gap: 8px;
	align-items: center;
}

/* Inner pills within format popup */
.block-editor-format-pill {
	display: flex;
	align-items: center;
	gap: 2px;
	padding: 2px;
	border-radius: 100px;
	background: var(--background-primary);
	flex: 1;
}

.block-editor-format-pill button {
	min-width: 0;
	flex: 1;
	height: 40px;
	border-radius: 100px !important;
}

.block-editor-format-pill button .svg-icon {
	width: 20px;
	height: 20px;
}

/* FAB */
.block-editor-fab {
	position: fixed;
	bottom: calc(60px + env(safe-area-inset-bottom, 0px));
	right: 16px;
	width: 48px;
	height: 48px;
	border-radius: 50%;
	background: var(--interactive-accent);
	color: var(--text-on-accent);
	border: none;
	box-shadow: 0 4px 12px rgba(0, 0, 0, 0.25);
	cursor: pointer;
	display: flex;
	align-items: center;
	justify-content: center;
	z-index: 50;
	touch-action: manipulation;
	transition: transform 0.15s ease;
}

.block-editor-fab:active {
	transform: scale(0.9);
}

.block-editor-fab .svg-icon {
	width: 22px;
	height: 22px;
	color: inherit;
	stroke: currentColor;
}

.block-editor-fab.toolbar-visible {
	bottom: calc(80px + env(safe-area-inset-bottom, 0px));
}

.block-editor-fab.active {
	background: var(--text-error);
}
`;
  document.head.appendChild(style);
  return style;
}
function removeStyles() {
  const el = document.getElementById("block-editor-styles");
  if (el)
    el.remove();
}

// src/main.ts
var BlockEditorPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.toolbar = null;
    this.fab = null;
    this.styleEl = null;
  }
  async onload() {
    var _a, _b, _c, _d, _e, _f;
    this.styleEl = injectStyles();
    const useTab = (_c = (_b = (_a = this.app.vault).getConfig) == null ? void 0 : _b.call(_a, "useTab")) != null ? _c : true;
    const tabSize = (_f = (_e = (_d = this.app.vault).getConfig) == null ? void 0 : _e.call(_d, "tabSize")) != null ? _f : 4;
    const indentUnit = useTab ? "	" : " ".repeat(tabSize);
    this.toolbar = new BlockEditorToolbar(indentUnit);
    this.fab = new BlockEditorFAB();
    document.body.appendChild(this.toolbar.el);
    document.body.appendChild(this.fab.el);
    const toolbar = this.toolbar;
    const fab = this.fab;
    const connectorPlugin = import_view3.ViewPlugin.fromClass(
      class {
        constructor(view) {
          this.view = view;
          toolbar.setView(view);
          fab.setView(view);
          this.syncState();
        }
        update(update) {
          toolbar.setView(this.view);
          fab.setView(this.view);
          this.syncState();
        }
        syncState() {
          const state = this.view.state.field(blockSelectionState);
          const hasSelection = state.selectedBlocks.size > 0;
          toolbar.updateVisibility(state.active, hasSelection);
          if (state.active) {
            document.body.classList.add("block-editor-active");
          } else {
            document.body.classList.remove("block-editor-active");
          }
          if (state.active) {
            fab.el.style.display = "flex";
            fab.updateAppearance(true);
            if (hasSelection) {
              fab.el.classList.add("toolbar-visible");
            } else {
              fab.el.classList.remove("toolbar-visible");
            }
          } else {
            fab.el.style.display = "none";
          }
          if (state.active && !hasSelection && !isDragSelecting()) {
            setTimeout(() => {
              const current = this.view.state.field(blockSelectionState);
              if (current.active && current.selectedBlocks.size === 0 && !isDragSelecting()) {
                setExitCooldown(this.view, Date.now() + 300);
                this.view.dispatch({
                  effects: [toggleBlockMode.of(false)]
                });
              }
            }, 0);
          }
        }
        destroy() {
          toolbar.hide();
          fab.el.style.display = "none";
          document.body.classList.remove("block-editor-active");
        }
      }
    );
    this.registerEditorExtension([
      blockSelectionState,
      blockModeTransactionFilter,
      blockSelectionGutter,
      blockHighlighter,
      connectorPlugin
    ]);
    const toggleBlock = (editor) => {
      const cmEditor = editor.cm;
      if (!cmEditor)
        return;
      const state = cmEditor.state.field(blockSelectionState);
      const newActive = !state.active;
      if (newActive) {
        const selected = /* @__PURE__ */ new Set();
        const hasFocus = cmEditor.hasFocus;
        if (hasFocus) {
          const sel = cmEditor.state.selection.main;
          const fromLine = cmEditor.state.doc.lineAt(sel.from).number;
          const toLine = cmEditor.state.doc.lineAt(sel.to).number;
          const visited = /* @__PURE__ */ new Set();
          for (let ln = fromLine; ln <= toLine; ln++) {
            if (visited.has(ln))
              continue;
            const [start, end] = getBlockWithChildren(cmEditor.state, ln, 4, true);
            for (let i = start; i <= end; i++) {
              visited.add(i);
              if (cmEditor.state.doc.line(i).text.trim() !== "") {
                selected.add(i);
              }
            }
          }
        }
        const effects = selected.size > 0 ? [toggleBlockMode.of(true), setBlockSelection.of(selected)] : [toggleBlockMode.of(true)];
        cmEditor.dispatch({ effects });
        cmEditor.contentDOM.blur();
      } else {
        cmEditor.dispatch({
          effects: [toggleBlockMode.of(false)]
        });
      }
    };
    this.addCommand({
      id: "toggle-block-mode",
      name: "Toggle Block Mode",
      icon: "layout-grid",
      editorCallback: toggleBlock
    });
    this.addRibbonIcon("layout-grid", "Toggle Block Mode", () => {
      const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
      if (markdownView) {
        toggleBlock(markdownView.editor);
      }
    });
  }
  onunload() {
    var _a, _b;
    (_a = this.toolbar) == null ? void 0 : _a.destroy();
    (_b = this.fab) == null ? void 0 : _b.destroy();
    document.body.classList.remove("block-editor-active");
    removeStyles();
  }
};
