/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BlockEditorPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");
var import_view3 = require("@codemirror/view");

// src/state.ts
var import_state = require("@codemirror/state");
var toggleBlockMode = import_state.StateEffect.define();
var toggleBlockSelection = import_state.StateEffect.define();
var setBlockSelection = import_state.StateEffect.define();
var clearBlockSelection = import_state.StateEffect.define();
var blockSelectionState = import_state.StateField.define({
  create() {
    return { active: false, selectedBlocks: /* @__PURE__ */ new Set() };
  },
  update(value, tr) {
    let result = value;
    for (const effect of tr.effects) {
      if (effect.is(toggleBlockMode)) {
        result = {
          active: effect.value,
          selectedBlocks: /* @__PURE__ */ new Set()
        };
      } else if (effect.is(toggleBlockSelection)) {
        const newSet = new Set(result.selectedBlocks);
        if (newSet.has(effect.value)) {
          newSet.delete(effect.value);
        } else {
          newSet.add(effect.value);
        }
        result = { active: result.active, selectedBlocks: newSet };
      } else if (effect.is(setBlockSelection)) {
        result = { active: result.active, selectedBlocks: effect.value };
      } else if (effect.is(clearBlockSelection)) {
        result = { active: result.active, selectedBlocks: /* @__PURE__ */ new Set() };
      }
    }
    return result;
  }
});

// src/gutter.ts
var import_view = require("@codemirror/view");
var import_state4 = require("@codemirror/state");

// src/operations.ts
var import_state2 = require("@codemirror/state");

// src/block-utils.ts
function getIndentLevel(line, tabSize, useTab) {
  let level = 0;
  let i = 0;
  if (useTab) {
    while (i < line.length && line[i] === "	") {
      level++;
      i++;
    }
  } else {
    let spaces = 0;
    while (i < line.length && line[i] === " ") {
      spaces++;
      i++;
    }
    level = Math.floor(spaces / tabSize);
  }
  return level;
}
function getLineText(state, lineNumber) {
  return state.doc.line(lineNumber).text;
}
function isBulletItem(text) {
  return /^(\s*)([-*+])\s/.test(text);
}
function isNumberedItem(text) {
  return /^(\s*)\d+\.\s/.test(text);
}
function isCheckboxItem(text) {
  return /^(\s*)([-*+])\s\[[ x]\]\s/.test(text);
}
function getLeadingWhitespace(text) {
  const match = text.match(/^(\s*)/);
  return match ? match[1] : "";
}
function getBlockWithChildren(state, lineNumber, tabSize, useTab) {
  const lineText = getLineText(state, lineNumber);
  const baseIndent = getIndentLevel(lineText, tabSize, useTab);
  const totalLines = state.doc.lines;
  let endLine = lineNumber;
  for (let i = lineNumber + 1; i <= totalLines; i++) {
    const text = getLineText(state, i);
    if (text.trim() === "") {
      let nextNonEmpty = i + 1;
      while (nextNonEmpty <= totalLines && getLineText(state, nextNonEmpty).trim() === "") {
        nextNonEmpty++;
      }
      if (nextNonEmpty <= totalLines && getIndentLevel(getLineText(state, nextNonEmpty), tabSize, useTab) > baseIndent) {
        endLine = i;
        continue;
      }
      break;
    }
    const indent = getIndentLevel(text, tabSize, useTab);
    if (indent > baseIndent) {
      endLine = i;
    } else {
      break;
    }
  }
  return [lineNumber, endLine];
}

// src/block-parser.ts
function lineIsBlank(text) {
  return text.trim() === "";
}
function lineIsHeading(text) {
  return /^#{1,6} /.test(text);
}
function lineIsListItem(text) {
  return /^(\s*)([-*+]|\d+\.)\s/.test(text);
}
function lineIsBlockquote(text) {
  return /^>/.test(text);
}
function lineIsCodeFence(text) {
  return /^(`{3,}|~{3,})/.test(text);
}
function lineIsTableRow(text) {
  return /^\s*\|/.test(text);
}
function lineIsBlockRef(text) {
  return /^\^[a-zA-Z0-9]+$/.test(text.trimEnd()) && !/ $/.test(text);
}
function getLineIndentLevel(text) {
  let i = 0;
  while (i < text.length && text[i] === "	")
    i++;
  if (i > 0)
    return i;
  let spaces = 0;
  while (spaces < text.length && text[spaces] === " ")
    spaces++;
  return Math.floor(spaces / 4);
}
function absorbBlockRef(doc, endLine) {
  const total = doc.lines;
  let i = endLine + 1;
  while (i <= total && lineIsBlank(doc.line(i).text))
    i++;
  if (i > total)
    return endLine;
  const refText = doc.line(i).text;
  if (!lineIsBlockRef(refText))
    return endLine;
  if (i + 1 > total || !lineIsBlank(doc.line(i + 1).text))
    return endLine;
  return i;
}
function parseDocument(doc, selectedLines) {
  const blocks = [];
  const total = doc.lines;
  let listGroupCounter = 0;
  let currentListGroup = null;
  let lastWasList = false;
  let ln = 1;
  const lt = (n) => doc.line(n).text;
  const markSelected = (start, end) => {
    if (!selectedLines)
      return false;
    for (let i = start; i <= end; i++) {
      if (selectedLines.has(i))
        return true;
    }
    return false;
  };
  const pushBlock = (type, start, end, extra) => {
    const lines = [];
    for (let i = start; i <= end; i++)
      lines.push(lt(i));
    blocks.push({
      type,
      startLine: start,
      endLine: end,
      lines,
      selected: markSelected(start, end),
      ...extra
    });
  };
  if (total >= 1 && /^---\s*$/.test(lt(1))) {
    let fmEnd = -1;
    for (let i = 2; i <= total; i++) {
      if (/^---\s*$/.test(lt(i))) {
        fmEnd = i;
        break;
      }
    }
    if (fmEnd !== -1) {
      pushBlock("frontmatter", 1, fmEnd);
      ln = fmEnd + 1;
    }
  }
  while (ln <= total) {
    const text = lt(ln);
    if (lineIsBlank(text)) {
      pushBlock("blank", ln, ln);
      lastWasList = false;
      currentListGroup = null;
      ln++;
      continue;
    }
    if (lineIsCodeFence(text)) {
      const fenceMatch = text.match(/^(`{3,}|~{3,})/);
      const fence = fenceMatch ? fenceMatch[1] : "```";
      const closePat = new RegExp(`^${fence[0]}{${fence.length},}`);
      let end = ln + 1;
      while (end <= total && !closePat.test(lt(end)))
        end++;
      if (end <= total) {
        pushBlock("code-block", ln, end);
        ln = end + 1;
      } else {
        pushBlock("code-block", ln, ln);
        ln++;
      }
      lastWasList = false;
      currentListGroup = null;
      continue;
    }
    if (lineIsHeading(text)) {
      let end = absorbBlockRef(doc, ln);
      pushBlock("heading", ln, end);
      lastWasList = false;
      currentListGroup = null;
      ln = end + 1;
      continue;
    }
    if (lineIsBlockquote(text)) {
      pushBlock("blockquote-line", ln, ln);
      lastWasList = false;
      currentListGroup = null;
      ln++;
      continue;
    }
    if (lineIsTableRow(text)) {
      let end = ln;
      while (end + 1 <= total && lineIsTableRow(lt(end + 1)))
        end++;
      end = absorbBlockRef(doc, end);
      pushBlock("table", ln, end);
      lastWasList = false;
      currentListGroup = null;
      ln = end + 1;
      continue;
    }
    if (lineIsListItem(text)) {
      if (!lastWasList) {
        listGroupCounter++;
        currentListGroup = listGroupCounter;
      }
      const group = currentListGroup;
      const indent = getLineIndentLevel(text);
      let end = absorbBlockRef(doc, ln);
      pushBlock("list-item", ln, end, { listGroup: group, indentLevel: indent });
      lastWasList = true;
      ln = end + 1;
      continue;
    }
    {
      let end = ln;
      while (end + 1 <= total && !lineIsBlank(lt(end + 1)) && !lineIsHeading(lt(end + 1)) && !lineIsListItem(lt(end + 1)) && !lineIsBlockquote(lt(end + 1)) && !lineIsCodeFence(lt(end + 1)) && !lineIsTableRow(lt(end + 1))) {
        end++;
      }
      end = absorbBlockRef(doc, end);
      pushBlock("paragraph", ln, end);
      lastWasList = false;
      currentListGroup = null;
      ln = end + 1;
    }
  }
  return blocks;
}
function needsBlankBetween(a, b) {
  if (a.type === "list-item" && b.type === "list-item" && a.listGroup === b.listGroup) {
    return false;
  }
  return true;
}
function reassignListGroups(blocks) {
  let counter = 0;
  let prevWasList = false;
  let currentGroup = 0;
  for (const b of blocks) {
    if (b.type === "list-item") {
      if (!prevWasList) {
        counter++;
        currentGroup = counter;
      }
      b.listGroup = currentGroup;
      prevWasList = true;
    } else if (b.type === "blank") {
      prevWasList = false;
    } else {
      prevWasList = false;
    }
  }
}
function renderBlocks(contentBlocks, baseLineNum) {
  const outputLines = [];
  const newSelectedLines = /* @__PURE__ */ new Set();
  for (let i = 0; i < contentBlocks.length; i++) {
    if (i > 0 && needsBlankBetween(contentBlocks[i - 1], contentBlocks[i])) {
      outputLines.push("");
    }
    const blockStart = outputLines.length;
    for (const line of contentBlocks[i].lines) {
      outputLines.push(line);
    }
    if (contentBlocks[i].selected) {
      for (let k = blockStart; k < outputLines.length; k++) {
        newSelectedLines.add(baseLineNum + k);
      }
    }
  }
  return { text: outputLines.join("\n"), newSelectedLines };
}

// src/operations.ts
var blockEditorTransaction = import_state2.Annotation.define();
function expandWithChildren(view, selectedLines) {
  const doc = view.state.doc;
  const allLines = /* @__PURE__ */ new Set();
  const useTab = true;
  const tabSize = 4;
  const sorted = Array.from(selectedLines).sort((a, b) => a - b);
  for (const lineNum of sorted) {
    if (allLines.has(lineNum))
      continue;
    const [start, end] = getBlockWithChildren(view.state, lineNum, tabSize, useTab);
    for (let i = start; i <= end; i++) {
      allLines.add(i);
    }
  }
  return Array.from(allLines).sort((a, b) => a - b);
}
function moveBlocksWithParser(view, selectedLines, direction) {
  const doc = view.state.doc;
  const fmEnd = getFrontmatterEndForOps(view);
  const allBlocks = parseDocument(doc, selectedLines);
  const contentBlocks = allBlocks.filter((b) => b.type !== "frontmatter");
  if (!contentBlocks.some((b) => b.selected))
    return false;
  if (contentBlocks.filter((b) => b.selected).every((b) => b.type === "list-item"))
    return false;
  const nonBlankContent = contentBlocks.filter((b) => b.type !== "blank");
  if (nonBlankContent.length === 0)
    return false;
  const selBlocks = [];
  const remainingBlocks = [];
  const remainingOrigIdx = [];
  nonBlankContent.forEach((b, i) => {
    if (b.selected) {
      selBlocks.push(b);
    } else {
      remainingBlocks.push(b);
      remainingOrigIdx.push(i);
    }
  });
  if (selBlocks.length === 0 || remainingBlocks.length === 0)
    return false;
  const firstSelIdx = nonBlankContent.findIndex((b) => b.selected);
  const lastSelIdx = nonBlankContent.length - 1 - [...nonBlankContent].reverse().findIndex((b) => b.selected);
  let reordered;
  if (direction === "up") {
    let pivotRemainingIdx = -1;
    for (let i = remainingOrigIdx.length - 1; i >= 0; i--) {
      if (remainingOrigIdx[i] < firstSelIdx) {
        pivotRemainingIdx = i;
        break;
      }
    }
    if (pivotRemainingIdx < 0)
      return false;
    if (fmEnd > 0 && remainingBlocks[pivotRemainingIdx].endLine <= fmEnd)
      return false;
    reordered = [
      ...remainingBlocks.slice(0, pivotRemainingIdx),
      ...selBlocks,
      ...remainingBlocks.slice(pivotRemainingIdx)
    ];
  } else {
    let pivotRemainingIdx = -1;
    for (let i = 0; i < remainingOrigIdx.length; i++) {
      if (remainingOrigIdx[i] > lastSelIdx) {
        pivotRemainingIdx = i;
        break;
      }
    }
    if (pivotRemainingIdx < 0)
      return false;
    reordered = [
      ...remainingBlocks.slice(0, pivotRemainingIdx + 1),
      ...selBlocks,
      ...remainingBlocks.slice(pivotRemainingIdx + 1)
    ];
  }
  return dispatchReorder(view, doc, reordered, fmEnd);
}
function dispatchReorder(view, doc, reorderedContent, fmEnd) {
  reassignListGroups(reorderedContent);
  const regionStart = fmEnd > 0 ? fmEnd + 1 : 1;
  const regionFrom = doc.line(regionStart).from;
  const { text, newSelectedLines } = renderBlocks(reorderedContent, regionStart);
  const origFull = doc.sliceString(regionFrom);
  let prefixLen = 0;
  while (prefixLen < Math.min(origFull.length, text.length) && origFull[prefixLen] === text[prefixLen]) {
    prefixLen++;
  }
  while (prefixLen > 0 && origFull[prefixLen - 1] !== "\n")
    prefixLen--;
  let suffixLen = 0;
  const maxSuffix = Math.min(origFull.length - prefixLen, text.length - prefixLen);
  while (suffixLen < maxSuffix && origFull[origFull.length - 1 - suffixLen] === text[text.length - 1 - suffixLen]) {
    suffixLen++;
  }
  while (suffixLen > 0 && origFull[origFull.length - suffixLen] !== "\n")
    suffixLen--;
  const changeFrom = regionFrom + prefixLen;
  const changeTo = regionFrom + origFull.length - suffixLen;
  const insertText = text.slice(prefixLen, text.length - suffixLen);
  view.dispatch({
    changes: { from: changeFrom, to: changeTo, insert: insertText },
    effects: [setBlockSelection.of(newSelectedLines)],
    annotations: [blockEditorTransaction.of(true)]
  });
  return true;
}
function moveBlocksUp(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  if (moveBlocksWithParser(view, selectedLines, "up"))
    return;
  const expanded = expandWithChildren(view, selectedLines);
  const firstLine = expanded[0];
  const lastLine = expanded[expanded.length - 1];
  if (firstLine <= 1)
    return;
  const doc = view.state.doc;
  const lineAbove = doc.line(firstLine - 1);
  const frontmatterEnd = getFrontmatterEndForOps(view);
  if (frontmatterEnd > 0 && firstLine - 1 <= frontmatterEnd)
    return;
  const firstSelectedLine = doc.line(firstLine);
  const lastSelectedLine = doc.line(lastLine);
  const useTab = true;
  const tabSize = 4;
  const indentStr = useTab ? "	" : " ".repeat(tabSize);
  const targetIndent = getIndentLevel(lineAbove.text, tabSize, useTab);
  const currentIndent = getIndentLevel(firstSelectedLine.text, tabSize, useTab);
  if (targetIndent > currentIndent) {
    const indentDelta2 = targetIndent - currentIndent;
    const blockTexts2 = [];
    for (let i = firstLine; i <= lastLine; i++) {
      blockTexts2.push(indentStr.repeat(indentDelta2) + doc.line(i).text);
    }
    const newText2 = blockTexts2.join("\n");
    view.dispatch({
      changes: { from: firstSelectedLine.from, to: lastSelectedLine.to, insert: newText2 },
      annotations: [blockEditorTransaction.of(true)]
    });
    return;
  }
  const indentDelta = targetIndent - currentIndent;
  const blockTexts = [];
  for (let i = firstLine; i <= lastLine; i++) {
    let text = doc.line(i).text;
    if (indentDelta < 0) {
      for (let d = 0; d < -indentDelta; d++) {
        if (text.startsWith("	")) {
          text = text.slice(1);
        } else if (text.startsWith(" ".repeat(tabSize))) {
          text = text.slice(tabSize);
        }
      }
    }
    blockTexts.push(text);
  }
  const newText = [...blockTexts, lineAbove.text].join("\n");
  const newSelection = new Set(Array.from(selectedLines).map((l) => l - 1));
  view.dispatch({
    changes: { from: lineAbove.from, to: lastSelectedLine.to, insert: newText },
    effects: [setBlockSelection.of(newSelection)],
    annotations: [blockEditorTransaction.of(true)]
  });
}
function moveBlocksDown(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  if (moveBlocksWithParser(view, selectedLines, "down"))
    return;
  const expanded = expandWithChildren(view, selectedLines);
  const firstLine = expanded[0];
  const lastLine = expanded[expanded.length - 1];
  if (lastLine >= view.state.doc.lines)
    return;
  const doc = view.state.doc;
  const lineBelow = doc.line(lastLine + 1);
  const firstSelectedLine = doc.line(firstLine);
  const lastSelectedLine = doc.line(lastLine);
  const useTab = true;
  const tabSize = 4;
  const indentStr = useTab ? "	" : " ".repeat(tabSize);
  const belowIndent = getIndentLevel(lineBelow.text, tabSize, useTab);
  const currentIndent = getIndentLevel(firstSelectedLine.text, tabSize, useTab);
  if (currentIndent > belowIndent) {
    const blockTexts2 = [];
    for (let i = firstLine; i <= lastLine; i++) {
      let text = doc.line(i).text;
      if (text.startsWith("	")) {
        text = text.slice(1);
      } else if (text.startsWith(" ".repeat(tabSize))) {
        text = text.slice(tabSize);
      }
      blockTexts2.push(text);
    }
    view.dispatch({
      changes: { from: firstSelectedLine.from, to: lastSelectedLine.to, insert: blockTexts2.join("\n") },
      annotations: [blockEditorTransaction.of(true)]
    });
    return;
  }
  let belowHasChildren = false;
  if (lastLine + 2 <= doc.lines) {
    const lineBelowNext = doc.line(lastLine + 2);
    if (lineBelowNext.text.trim() !== "" && getIndentLevel(lineBelowNext.text, tabSize, useTab) > belowIndent) {
      belowHasChildren = true;
    }
  }
  const targetIndent = belowHasChildren && currentIndent <= belowIndent ? belowIndent + 1 : belowIndent;
  const indentDelta = targetIndent - currentIndent;
  const blockTexts = [];
  for (let i = firstLine; i <= lastLine; i++) {
    let text = doc.line(i).text;
    if (indentDelta > 0) {
      text = indentStr.repeat(indentDelta) + text;
    }
    blockTexts.push(text);
  }
  const newText = [lineBelow.text, ...blockTexts].join("\n");
  const newSelection = new Set(Array.from(selectedLines).map((l) => l + 1));
  view.dispatch({
    changes: { from: firstSelectedLine.from, to: lineBelow.to, insert: newText },
    effects: [setBlockSelection.of(newSelection)],
    annotations: [blockEditorTransaction.of(true)]
  });
}
function indentBlocks(view, selectedLines, indentUnit) {
  if (selectedLines.size === 0)
    return;
  const expanded = expandWithChildren(view, selectedLines);
  const changes = [];
  const doc = view.state.doc;
  for (const lineNum of expanded) {
    const line = doc.line(lineNum);
    changes.push({ from: line.from, to: line.from, insert: indentUnit });
  }
  view.dispatch({
    changes,
    annotations: [blockEditorTransaction.of(true)]
  });
}
function outdentBlocks(view, selectedLines, indentUnit) {
  if (selectedLines.size === 0)
    return;
  const expanded = expandWithChildren(view, selectedLines);
  const changes = [];
  const doc = view.state.doc;
  for (const lineNum of expanded) {
    const line = doc.line(lineNum);
    const text = line.text;
    if (text.startsWith("	")) {
      changes.push({ from: line.from, to: line.from + 1, insert: "" });
    } else {
      let spacesToRemove = 0;
      for (let i = 0; i < Math.min(indentUnit.length, text.length); i++) {
        if (text[i] === " ")
          spacesToRemove++;
        else
          break;
      }
      if (spacesToRemove > 0) {
        changes.push({ from: line.from, to: line.from + spacesToRemove, insert: "" });
      }
    }
  }
  if (changes.length > 0) {
    view.dispatch({
      changes,
      annotations: [blockEditorTransaction.of(true)]
    });
  }
}
function setHeadingLevel(view, selectedLines, level) {
  if (selectedLines.size === 0)
    return;
  const doc = view.state.doc;
  const changes = [];
  const sorted = Array.from(selectedLines).sort((a, b) => a - b);
  for (const lineNum of sorted) {
    if (lineNum < 1 || lineNum > doc.lines)
      continue;
    const line = doc.line(lineNum);
    const content = line.text.replace(/^#{1,6}\s+/, "");
    const prefix = level > 0 ? "#".repeat(level) + " " : "";
    const newText = prefix + content;
    if (newText !== line.text) {
      changes.push({ from: line.from, to: line.to, insert: newText });
    }
  }
  if (changes.length > 0) {
    view.dispatch({
      changes,
      annotations: [blockEditorTransaction.of(true)]
    });
  }
}
function toggleBulletList(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const doc = view.state.doc;
  const changes = [];
  const allBullets = Array.from(selectedLines).every((l) => isBulletItem(doc.line(l).text));
  for (const lineNum of selectedLines) {
    const line = doc.line(lineNum);
    const text = line.text;
    const ws = getLeadingWhitespace(text);
    if (allBullets) {
      const newText = text.replace(/^(\s*)([-*+])\s/, "$1");
      changes.push({ from: line.from, to: line.to, insert: newText });
    } else {
      let content = text.replace(/^(\s*)([-*+]|\d+\.)\s(\[[ x]\]\s)?/, "$1");
      changes.push({ from: line.from, to: line.to, insert: ws + "- " + content.trimStart() });
    }
  }
  view.dispatch({
    changes,
    annotations: [blockEditorTransaction.of(true)]
  });
}
function toggleNumberedList(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const doc = view.state.doc;
  const changes = [];
  const allNumbered = Array.from(selectedLines).every((l) => isNumberedItem(doc.line(l).text));
  let counter = 1;
  const sorted = Array.from(selectedLines).sort((a, b) => a - b);
  for (const lineNum of sorted) {
    const line = doc.line(lineNum);
    const text = line.text;
    const ws = getLeadingWhitespace(text);
    if (allNumbered) {
      const newText = text.replace(/^(\s*)\d+\.\s/, "$1");
      changes.push({ from: line.from, to: line.to, insert: newText });
    } else {
      let content = text.replace(/^(\s*)([-*+]|\d+\.)\s(\[[ x]\]\s)?/, "$1");
      changes.push({ from: line.from, to: line.to, insert: ws + counter + ". " + content.trimStart() });
      counter++;
    }
  }
  view.dispatch({
    changes,
    annotations: [blockEditorTransaction.of(true)]
  });
}
function toggleCheckbox(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const doc = view.state.doc;
  const changes = [];
  const allCheckbox = Array.from(selectedLines).every((l) => isCheckboxItem(doc.line(l).text));
  for (const lineNum of selectedLines) {
    const line = doc.line(lineNum);
    const text = line.text;
    const ws = getLeadingWhitespace(text);
    if (allCheckbox) {
      const newText = text.replace(/^(\s*)([-*+])\s\[[ x]\]\s/, "$1$2 ");
      changes.push({ from: line.from, to: line.to, insert: newText });
    } else {
      let content = text.replace(/^(\s*)([-*+]|\d+\.)\s(\[[ x]\]\s)?/, "$1");
      changes.push({ from: line.from, to: line.to, insert: ws + "- [ ] " + content.trimStart() });
    }
  }
  view.dispatch({
    changes,
    annotations: [blockEditorTransaction.of(true)]
  });
}
function deleteBlocks(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const expanded = expandWithChildren(view, selectedLines);
  const doc = view.state.doc;
  const changes = [];
  for (const lineNum of expanded) {
    const line = doc.line(lineNum);
    let from = line.from;
    let to = line.to;
    if (to < doc.length) {
      to += 1;
    } else if (from > 0) {
      from -= 1;
    }
    changes.push({ from, to, insert: "" });
  }
  view.dispatch({
    changes,
    effects: [setBlockSelection.of(/* @__PURE__ */ new Set())],
    annotations: [blockEditorTransaction.of(true)]
  });
}
function undoAction(view) {
  const commands = require("@codemirror/commands");
  commands.undo(view);
}
function redoAction(view) {
  const commands = require("@codemirror/commands");
  commands.redo(view);
}
function copyBlocks(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const expanded = expandWithChildren(view, selectedLines);
  const doc = view.state.doc;
  const lines = expanded.map((l) => doc.line(l).text);
  const text = lines.join("\n");
  navigator.clipboard.writeText(text);
}
function cutBlocks(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  copyBlocks(view, selectedLines);
  deleteBlocks(view, selectedLines);
}
function toggleQuote(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const doc = view.state.doc;
  const changes = [];
  const sorted = Array.from(selectedLines).sort((a, b) => a - b);
  const firstLine = sorted[0];
  const lastLine = sorted[sorted.length - 1];
  const allLines = [];
  for (let i = firstLine; i <= lastLine; i++) {
    const text = doc.line(i).text;
    if (selectedLines.has(i) || text.trim() === "" || text.trim() === ">") {
      allLines.push(i);
    }
  }
  const allQuoted = sorted.every((l) => {
    const text = doc.line(l).text;
    return text.startsWith("> ") || text === ">";
  });
  for (const lineNum of allLines) {
    const line = doc.line(lineNum);
    const text = line.text;
    if (allQuoted) {
      changes.push({ from: line.from, to: line.to, insert: text.replace(/^> ?/, "") });
    } else {
      if (text.startsWith("> ")) {
      } else if (text.trim() === "" || text.trim() === ">") {
        changes.push({ from: line.from, to: line.to, insert: ">" });
      } else {
        changes.push({ from: line.from, to: line.to, insert: "> " + text });
      }
    }
  }
  if (changes.length > 0) {
    view.dispatch({
      changes,
      annotations: [blockEditorTransaction.of(true)]
    });
  }
}
function toggleInlineFormat(view, selectedLines, marker) {
  if (selectedLines.size === 0)
    return;
  const doc = view.state.doc;
  const changes = [];
  const sorted = Array.from(selectedLines).sort((a, b) => a - b);
  const allWrapped = sorted.every((ln) => {
    const text = doc.line(ln).text;
    const content = getContentPart(text);
    return content.startsWith(marker) && content.endsWith(marker) && content.length >= marker.length * 2;
  });
  for (const lineNum of sorted) {
    if (lineNum < 1 || lineNum > doc.lines)
      continue;
    const line = doc.line(lineNum);
    const text = line.text;
    const prefixEnd = getContentStartIndex(text);
    const prefix = text.slice(0, prefixEnd);
    const content = text.slice(prefixEnd);
    let newContent;
    if (allWrapped) {
      newContent = content.slice(marker.length, content.length - marker.length);
    } else {
      let stripped = content;
      if (stripped.startsWith(marker) && stripped.endsWith(marker) && stripped.length >= marker.length * 2) {
        stripped = stripped.slice(marker.length, stripped.length - marker.length);
      }
      newContent = marker + stripped + marker;
    }
    const newText = prefix + newContent;
    if (newText !== text) {
      changes.push({ from: line.from, to: line.to, insert: newText });
    }
  }
  if (changes.length > 0) {
    view.dispatch({
      changes,
      annotations: [blockEditorTransaction.of(true)]
    });
  }
}
function getContentPart(text) {
  return text.slice(getContentStartIndex(text));
}
function getContentStartIndex(text) {
  const wsMatch = text.match(/^(\s*)/);
  let idx = wsMatch ? wsMatch[1].length : 0;
  const rest = text.slice(idx);
  const headingMatch = rest.match(/^(#{1,6}\s+)/);
  if (headingMatch) {
    idx += headingMatch[1].length;
    return idx;
  }
  const listMatch = rest.match(/^((?:[-*+]|\d+\.)\s+(?:\[[ x]\]\s+)?)/);
  if (listMatch) {
    idx += listMatch[1].length;
    return idx;
  }
  const quoteMatch = rest.match(/^(>\s+)/);
  if (quoteMatch) {
    idx += quoteMatch[1].length;
    return idx;
  }
  return idx;
}
function toggleCodeFormat(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  toggleInlineFormat(view, selectedLines, "`");
}
function getFrontmatterEndForOps(view) {
  const doc = view.state.doc;
  if (doc.lines < 1)
    return 0;
  if (!/^---\s*$/.test(doc.line(1).text))
    return 0;
  for (let i = 2; i <= doc.lines; i++) {
    if (/^---\s*$/.test(doc.line(i).text))
      return i;
  }
  return 0;
}
function progressiveSelectAll(view, selectedLines) {
  const doc = view.state.doc;
  const frontmatterEnd = getFrontmatterEndForOps(view);
  const useTab = true;
  const tabSize = 4;
  if (selectedLines.size === 0) {
    const allLines2 = /* @__PURE__ */ new Set();
    for (let i = frontmatterEnd + 1; i <= doc.lines; i++) {
      if (doc.line(i).text.trim() !== "")
        allLines2.add(i);
    }
    view.dispatch({ effects: [setBlockSelection.of(allLines2)] });
    return;
  }
  const sorted = Array.from(selectedLines).sort((a, b) => a - b);
  let minIndent = Infinity;
  for (const ln of sorted) {
    const indent = getIndentLevel(doc.line(ln).text, tabSize, useTab);
    if (indent < minIndent)
      minIndent = indent;
  }
  if (minIndent > 0) {
    let parentLine = -1;
    for (let i = sorted[0] - 1; i > frontmatterEnd; i--) {
      const text = doc.line(i).text;
      if (text.trim() === "")
        continue;
      const indent = getIndentLevel(text, tabSize, useTab);
      if (indent < minIndent) {
        parentLine = i;
        break;
      }
    }
    if (parentLine !== -1) {
      const [scopeStart, scopeEnd] = getBlockWithChildren(view.state, parentLine, tabSize, useTab);
      let allSiblingsSelected = true;
      for (let i = scopeStart; i <= scopeEnd; i++) {
        const text = doc.line(i).text;
        if (text.trim() === "")
          continue;
        const indent = getIndentLevel(text, tabSize, useTab);
        if (indent === minIndent && !selectedLines.has(i)) {
          allSiblingsSelected = false;
          break;
        }
      }
      if (!allSiblingsSelected) {
        const newSelection = /* @__PURE__ */ new Set();
        for (let i = scopeStart; i <= scopeEnd; i++) {
          const text = doc.line(i).text;
          if (text.trim() === "")
            continue;
          if (getIndentLevel(text, tabSize, useTab) >= minIndent) {
            newSelection.add(i);
          }
        }
        view.dispatch({ effects: [setBlockSelection.of(newSelection)] });
        return;
      } else {
        const newSelection = /* @__PURE__ */ new Set();
        for (let i = scopeStart; i <= scopeEnd; i++) {
          if (doc.line(i).text.trim() !== "")
            newSelection.add(i);
        }
        view.dispatch({ effects: [setBlockSelection.of(newSelection)] });
        return;
      }
    }
  }
  const isListContent = (text) => {
    return isBulletItem(text) || isNumberedItem(text) || isCheckboxItem(text) || getIndentLevel(text, tabSize, useTab) > 0;
  };
  let regionStart = sorted[0];
  for (let i = sorted[0] - 1; i > frontmatterEnd; i--) {
    const text = doc.line(i).text;
    if (text.trim() === "")
      break;
    if (!isListContent(text) && !selectedLines.has(i))
      break;
    regionStart = i;
  }
  const [, lastChildEnd] = getBlockWithChildren(view.state, sorted[sorted.length - 1], tabSize, useTab);
  let regionEnd = Math.max(sorted[sorted.length - 1], lastChildEnd);
  for (let i = regionEnd + 1; i <= doc.lines; i++) {
    const text = doc.line(i).text;
    if (text.trim() === "")
      break;
    if (!isListContent(text))
      break;
    regionEnd = i;
  }
  const regionSelection = /* @__PURE__ */ new Set();
  for (let i = regionStart; i <= regionEnd; i++) {
    if (doc.line(i).text.trim() !== "")
      regionSelection.add(i);
  }
  if (regionSelection.size > selectedLines.size) {
    view.dispatch({ effects: [setBlockSelection.of(regionSelection)] });
    return;
  }
  const allLines = /* @__PURE__ */ new Set();
  for (let i = frontmatterEnd + 1; i <= doc.lines; i++) {
    if (doc.line(i).text.trim() !== "")
      allLines.add(i);
  }
  view.dispatch({ effects: [setBlockSelection.of(allLines)] });
}
function getLinePrefix(text) {
  const wsMatch = text.match(/^(\s*)/);
  const ws = wsMatch ? wsMatch[1] : "";
  const rest = text.slice(ws.length);
  const checkboxMatch = rest.match(/^([-*+]\s+\[[ x]\]\s+)/);
  if (checkboxMatch)
    return ws + checkboxMatch[1];
  const bulletMatch = rest.match(/^([-*+]\s+)/);
  if (bulletMatch)
    return ws + bulletMatch[1];
  const numberedMatch = rest.match(/^(\d+\.\s+)/);
  if (numberedMatch)
    return ws + "1. ";
  const quoteMatch = rest.match(/^(>\s+)/);
  if (quoteMatch)
    return ws + quoteMatch[1];
  return ws;
}
function isListPrefix(prefix) {
  const trimmed = prefix.trimStart();
  return /^[-*+]\s/.test(trimmed) || /^\d+\.\s/.test(trimmed);
}
function insertAbove(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const sorted = Array.from(selectedLines).sort((a, b) => a - b);
  const topLine = view.state.doc.line(sorted[0]);
  const prefix = getLinePrefix(topLine.text);
  const isList = isListPrefix(prefix);
  const insertPos = topLine.from;
  const insertText = isList ? prefix + "\n" : prefix + "\n\n";
  view.dispatch({
    changes: { from: insertPos, to: insertPos, insert: insertText },
    selection: { anchor: insertPos + prefix.length },
    annotations: [blockEditorTransaction.of(true)],
    effects: [toggleBlockMode.of(false)]
  });
  view.focus();
}
function insertBelow(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const sorted = Array.from(selectedLines).sort((a, b) => a - b);
  const bottomLine = view.state.doc.line(sorted[sorted.length - 1]);
  const prefix = getLinePrefix(bottomLine.text);
  const isList = isListPrefix(prefix);
  const insertPos = bottomLine.to;
  const insertText = isList ? "\n" + prefix : "\n\n" + prefix;
  const cursorOffset = isList ? 1 + prefix.length : 2 + prefix.length;
  view.dispatch({
    changes: { from: insertPos, to: insertPos, insert: insertText },
    selection: { anchor: insertPos + cursorOffset },
    annotations: [blockEditorTransaction.of(true)],
    effects: [toggleBlockMode.of(false)]
  });
  view.focus();
}
function editBlock(view, selectedLines) {
  if (selectedLines.size === 0)
    return;
  const sorted = Array.from(selectedLines).sort((a, b) => a - b);
  const topLine = view.state.doc.line(sorted[0]);
  view.dispatch({
    selection: { anchor: topLine.to },
    annotations: [blockEditorTransaction.of(true)],
    effects: [toggleBlockMode.of(false)]
  });
  view.focus();
}

// src/gutter.ts
var gutterExitCooldownUntil = 0;
function setExitCooldown(_view, until) {
  gutterExitCooldownUntil = until;
}
var dragSelectActive = false;
function isDragSelecting() {
  return dragSelectActive;
}
function getFrontmatterEnd(view) {
  const doc = view.state.doc;
  if (doc.lines < 1)
    return 0;
  if (doc.line(1).text.trim() !== "---")
    return 0;
  for (let i = 2; i <= doc.lines; i++) {
    if (doc.line(i).text.trim() === "---")
      return i;
  }
  return 0;
}
var blockModeTransactionFilter = import_state4.EditorState.transactionFilter.of((tr) => {
  const state = tr.startState.field(blockSelectionState);
  if (!state.active)
    return tr;
  if (tr.annotation(blockEditorTransaction))
    return tr;
  if (tr.effects.length > 0)
    return tr;
  if (tr.docChanged) {
    const userEvent = tr.annotation(import_state4.Transaction.userEvent);
    if (userEvent)
      return [];
    return tr;
  }
  return tr;
});
var blockSelectionGutter = import_view.ViewPlugin.fromClass(
  class {
    constructor(view) {
      this.view = view;
      this.pointerStart = null;
      // Long-press to enter block mode
      this.longPressTimer = null;
      this.longPressStart = null;
      // Drag-select across circles
      this.circlePositions = [];
      this.dragAnchorLine = null;
      this.dragSelectionBefore = /* @__PURE__ */ new Set();
      this.dragIsDeselecting = false;
      this.dragLastLine = null;
      // Auto-scroll during drag
      this.autoScrollRAF = null;
      this.autoScrollSpeed = 0;
      this.lastDragClientY = 0;
      this.container = document.createElement("div");
      this.container.className = "block-editor-gutter";
      this.container.style.display = "none";
      document.body.appendChild(this.container);
      this.scrollHandler = () => {
        if (this.view.state.field(blockSelectionState).active) {
          this.buildGutter();
        }
      };
      view.scrollDOM.addEventListener("scroll", this.scrollHandler);
      this.focusHandler = () => {
        if (this.view.state.field(blockSelectionState).active || Date.now() < gutterExitCooldownUntil) {
          setTimeout(() => this.view.contentDOM.blur(), 0);
        }
      };
      view.contentDOM.addEventListener("focus", this.focusHandler);
      this.contentPointerDownHandler = (e) => {
        if (!this.view.state.field(blockSelectionState).active)
          return;
        if (e.target.closest(".block-editor-gutter-circle"))
          return;
        this.pointerStart = { x: e.clientX, y: e.clientY };
      };
      this.contentPointerUpHandler = (e) => {
        if (!this.pointerStart)
          return;
        if (!this.view.state.field(blockSelectionState).active) {
          this.pointerStart = null;
          return;
        }
        const dx = e.clientX - this.pointerStart.x;
        const dy = e.clientY - this.pointerStart.y;
        this.pointerStart = null;
        if (Math.sqrt(dx * dx + dy * dy) > 10)
          return;
        const pos = this.view.posAtCoords({ x: e.clientX, y: e.clientY });
        if (pos === null)
          return;
        const lineNum = this.view.state.doc.lineAt(pos).number;
        const frontmatterEnd = getFrontmatterEnd(this.view);
        if (lineNum <= frontmatterEnd)
          return;
        e.preventDefault();
        this.toggleLineWithChildren(lineNum);
      };
      view.contentDOM.addEventListener("pointerdown", this.contentPointerDownHandler);
      view.contentDOM.addEventListener("pointerup", this.contentPointerUpHandler);
      this.touchStartHandler = (e) => {
        if (this.view.state.field(blockSelectionState).active)
          return;
        if (this.view.hasFocus)
          return;
        const touch = e.touches[0];
        this.longPressStart = { x: touch.clientX, y: touch.clientY };
        this.view.contentDOM.style.userSelect = "none";
        this.view.contentDOM.style.webkitUserSelect = "none";
        this.view.contentDOM.style.webkitTouchCallout = "none";
        this.longPressTimer = setTimeout(() => {
          this.longPressTimer = null;
          if (!this.longPressStart)
            return;
          const pos = this.view.posAtCoords(this.longPressStart);
          if (pos === null) {
            this.clearLongPress();
            return;
          }
          const lineNum = this.view.state.doc.lineAt(pos).number;
          const frontmatterEnd = getFrontmatterEnd(this.view);
          if (lineNum <= frontmatterEnd) {
            this.clearLongPress();
            return;
          }
          const [start, end] = getBlockWithChildren(this.view.state, lineNum, 4, true);
          const selected = /* @__PURE__ */ new Set();
          for (let i = start; i <= end; i++) {
            if (this.view.state.doc.line(i).text.trim() !== "") {
              selected.add(i);
            }
          }
          this.view.dispatch({
            effects: [toggleBlockMode.of(true), setBlockSelection.of(selected)]
          });
          const winSel = window.getSelection();
          if (winSel)
            winSel.removeAllRanges();
          this.view.contentDOM.blur();
          this.clearLongPress();
        }, 800);
      };
      this.touchMoveHandler = (e) => {
        if (!this.longPressStart || !this.longPressTimer)
          return;
        const touch = e.touches[0];
        const dx = touch.clientX - this.longPressStart.x;
        const dy = touch.clientY - this.longPressStart.y;
        if (Math.sqrt(dx * dx + dy * dy) > 10) {
          this.cancelLongPress();
        }
      };
      this.touchEndHandler = () => {
        this.cancelLongPress();
      };
      view.contentDOM.addEventListener("touchstart", this.touchStartHandler, { passive: true });
      view.contentDOM.addEventListener("touchmove", this.touchMoveHandler, { passive: true });
      view.contentDOM.addEventListener("touchend", this.touchEndHandler);
      view.contentDOM.addEventListener("touchcancel", this.touchEndHandler);
      this.dragMoveHandler = (e) => {
        if (this.dragAnchorLine === null)
          return;
        this.lastDragClientY = e.clientY;
        if (!dragSelectActive)
          dragSelectActive = true;
        this.updateDragSelection(e.clientY);
        this.updateAutoScroll(e.clientY);
      };
      this.dragEndHandler = () => {
        this.stopAutoScroll();
        this.dragAnchorLine = null;
        this.dragLastLine = null;
        dragSelectActive = false;
      };
      document.addEventListener("pointermove", this.dragMoveHandler);
      document.addEventListener("pointerup", this.dragEndHandler);
      document.addEventListener("pointercancel", this.dragEndHandler);
    }
    update(update) {
      const state = update.state.field(blockSelectionState);
      const prev = update.startState.field(blockSelectionState);
      if (state.active && !prev.active) {
        this.view.contentDOM.blur();
      }
      if (state.active !== prev.active || state.selectedBlocks !== prev.selectedBlocks || update.docChanged || update.viewportChanged || update.geometryChanged) {
        this.buildGutter();
      }
    }
    /**
     * Toggle selection for a line and its children.
     * Selecting a parent auto-selects all indented children below it.
     * If the parent+children are already all selected, deselect them all.
     */
    clearLongPress() {
      this.longPressStart = null;
      this.view.contentDOM.style.userSelect = "";
      this.view.contentDOM.style.webkitUserSelect = "";
      this.view.contentDOM.style.webkitTouchCallout = "";
    }
    cancelLongPress() {
      if (this.longPressTimer) {
        clearTimeout(this.longPressTimer);
        this.longPressTimer = null;
      }
      this.clearLongPress();
    }
    /**
     * Find the nearest circle line number for a given screen Y position.
     */
    findNearestCircleLine(y) {
      let best = null;
      let bestDist = Infinity;
      for (const cp of this.circlePositions) {
        const dist = Math.abs(y - cp.centerY);
        if (dist < bestDist) {
          bestDist = dist;
          best = cp.lineNum;
        }
      }
      const maxDist = this.autoScrollSpeed !== 0 ? 200 : 40;
      return bestDist < maxDist ? best : null;
    }
    /**
     * Update selection based on current drag Y position.
     */
    updateDragSelection(clientY) {
      this.rebuildCirclePositions();
      const lineNum = this.findNearestCircleLine(clientY);
      if (lineNum === null || lineNum === this.dragLastLine)
        return;
      this.dragLastLine = lineNum;
      const newSet = new Set(this.dragSelectionBefore);
      const lo = Math.min(this.dragAnchorLine, lineNum);
      const hi = Math.max(this.dragAnchorLine, lineNum);
      const doc = this.view.state.doc;
      const dragLines = /* @__PURE__ */ new Set();
      for (let ln = lo; ln <= hi; ln++) {
        const [start, end] = getBlockWithChildren(this.view.state, ln, 4, true);
        for (let i = start; i <= end; i++) {
          if (i >= 1 && i <= doc.lines && doc.line(i).text.trim() !== "") {
            dragLines.add(i);
          }
        }
      }
      if (this.dragIsDeselecting) {
        for (const ln of dragLines) {
          newSet.delete(ln);
        }
      } else {
        for (const ln of dragLines) {
          newSet.add(ln);
        }
      }
      if (navigator.vibrate)
        navigator.vibrate(5);
      this.view.dispatch({
        effects: [setBlockSelection.of(newSet)]
      });
    }
    /**
     * Compute the set of line numbers that should have a gutter circle.
     * - table, paragraph, heading: only the first line of the block
     * - code-block: every line (each gets its own circle)
     * - blockquote-line, list-item: each is already one line, so start line
     * - blank / frontmatter: no circle
     */
    getCircleLines() {
      const doc = this.view.state.doc;
      const blocks = parseDocument(doc);
      const circleLines = /* @__PURE__ */ new Set();
      for (const block of blocks) {
        if (block.type === "frontmatter" || block.type === "blank")
          continue;
        if (block.type === "code-block") {
          for (let ln = block.startLine; ln <= block.endLine; ln++) {
            if (doc.line(ln).text.trim() !== "")
              circleLines.add(ln);
          }
        } else {
          circleLines.add(block.startLine);
        }
      }
      return circleLines;
    }
    rebuildCirclePositions() {
      const doc = this.view.state.doc;
      const contentTop = this.view.contentDOM.getBoundingClientRect().top;
      const scrollerRect = this.view.scrollDOM.getBoundingClientRect();
      const circleLines = this.getCircleLines();
      this.circlePositions = [];
      const { from, to } = this.view.viewport;
      const startLine = doc.lineAt(from).number;
      const endLine = doc.lineAt(to).number;
      for (let lineNum = startLine; lineNum <= endLine; lineNum++) {
        if (!circleLines.has(lineNum))
          continue;
        const line = doc.line(lineNum);
        const block = this.view.lineBlockAt(line.from);
        const screenY = contentTop + block.top;
        if (screenY + block.height < scrollerRect.top)
          continue;
        if (screenY > scrollerRect.bottom)
          continue;
        const circleTop = screenY + (block.height - 28) / 2;
        this.circlePositions.push({ lineNum, centerY: circleTop + 14 });
      }
    }
    /**
     * Start or update auto-scrolling based on pointer proximity to edges.
     */
    updateAutoScroll(clientY) {
      const scrollerRect = this.view.scrollDOM.getBoundingClientRect();
      const edgeZone = 150;
      const maxSpeed = 30;
      if (clientY < scrollerRect.top + edgeZone) {
        const proximity = (scrollerRect.top + edgeZone - clientY) / edgeZone;
        this.autoScrollSpeed = -maxSpeed * Math.min(proximity, 1);
      } else if (clientY > scrollerRect.bottom - edgeZone) {
        const proximity = (clientY - (scrollerRect.bottom - edgeZone)) / edgeZone;
        this.autoScrollSpeed = maxSpeed * Math.min(proximity, 1);
      } else {
        this.stopAutoScroll();
        return;
      }
      if (this.autoScrollRAF === null) {
        this.autoScrollLoop();
      }
    }
    autoScrollLoop() {
      if (this.dragAnchorLine === null || this.autoScrollSpeed === 0) {
        this.stopAutoScroll();
        return;
      }
      this.view.scrollDOM.scrollTop += this.autoScrollSpeed;
      this.buildGutter();
      this.updateDragSelection(this.lastDragClientY);
      this.autoScrollRAF = requestAnimationFrame(() => this.autoScrollLoop());
    }
    stopAutoScroll() {
      this.autoScrollSpeed = 0;
      if (this.autoScrollRAF !== null) {
        cancelAnimationFrame(this.autoScrollRAF);
        this.autoScrollRAF = null;
      }
    }
    /**
     * Start drag-select from a circle. Called BEFORE toggleLineWithChildren
     * so we can check if the line was already selected (deselect mode) or not.
     */
    startDragSelect(lineNum) {
      const state = this.view.state.field(blockSelectionState);
      this.dragIsDeselecting = state.selectedBlocks.has(lineNum);
      this.dragSelectionBefore = new Set(state.selectedBlocks);
      this.dragAnchorLine = lineNum;
      this.dragLastLine = lineNum;
    }
    toggleLineWithChildren(lineNum) {
      const state = this.view.state.field(blockSelectionState);
      const doc = this.view.state.doc;
      const blocks = parseDocument(doc);
      const block = blocks.find((b) => b.startLine === lineNum);
      let start;
      let end;
      if (block && block.type !== "blank" && block.type !== "frontmatter") {
        start = block.startLine;
        end = block.endLine;
      } else {
        const [s, e] = getBlockWithChildren(this.view.state, lineNum, 4, true);
        start = s;
        end = e;
      }
      const newSet = new Set(state.selectedBlocks);
      let allSelected = true;
      for (let i = start; i <= end; i++) {
        const lineText = doc.line(i).text;
        if (lineText.trim() === "")
          continue;
        if (!newSet.has(i)) {
          allSelected = false;
          break;
        }
      }
      if (allSelected) {
        for (let i = start; i <= end; i++) {
          newSet.delete(i);
        }
      } else {
        for (let i = start; i <= end; i++) {
          const lineText = doc.line(i).text;
          if (lineText.trim() === "")
            continue;
          newSet.add(i);
        }
      }
      if (navigator.vibrate) {
        navigator.vibrate(5);
      }
      this.view.dispatch({
        effects: [setBlockSelection.of(newSet)]
      });
    }
    buildGutter() {
      const state = this.view.state.field(blockSelectionState);
      this.container.innerHTML = "";
      if (!state.active) {
        this.container.style.display = "none";
        return;
      }
      this.container.style.display = "block";
      const { from, to } = this.view.viewport;
      const doc = this.view.state.doc;
      const startLine = doc.lineAt(from).number;
      const endLine = doc.lineAt(to).number;
      const contentTop = this.view.contentDOM.getBoundingClientRect().top;
      const scrollerRect = this.view.scrollDOM.getBoundingClientRect();
      const circleLeft = scrollerRect.right - 44;
      this.circlePositions = [];
      const circleLines = this.getCircleLines();
      for (let lineNum = startLine; lineNum <= endLine; lineNum++) {
        if (!circleLines.has(lineNum))
          continue;
        const line = doc.line(lineNum);
        const block = this.view.lineBlockAt(line.from);
        const screenY = contentTop + block.top;
        if (screenY + block.height < scrollerRect.top)
          continue;
        if (screenY > scrollerRect.bottom)
          continue;
        const circle = document.createElement("div");
        circle.className = "block-editor-gutter-circle";
        if (state.selectedBlocks.has(lineNum)) {
          circle.classList.add("selected");
        }
        const circleTop = screenY + (block.height - 28) / 2;
        circle.style.top = circleTop + "px";
        circle.style.left = circleLeft + "px";
        this.circlePositions.push({ lineNum, centerY: circleTop + 14 });
        circle.addEventListener("pointerdown", (e) => {
          e.preventDefault();
          e.stopPropagation();
          this.startDragSelect(lineNum);
          this.toggleLineWithChildren(lineNum);
        });
        circle.addEventListener("mousedown", (e) => {
          e.preventDefault();
          e.stopPropagation();
        });
        circle.addEventListener("touchstart", (e) => {
          e.preventDefault();
          e.stopPropagation();
        }, { passive: false });
        this.container.appendChild(circle);
      }
    }
    destroy() {
      this.cancelLongPress();
      this.stopAutoScroll();
      this.dragAnchorLine = null;
      this.container.remove();
      this.view.scrollDOM.removeEventListener("scroll", this.scrollHandler);
      this.view.contentDOM.removeEventListener("focus", this.focusHandler);
      this.view.contentDOM.removeEventListener("pointerdown", this.contentPointerDownHandler);
      this.view.contentDOM.removeEventListener("pointerup", this.contentPointerUpHandler);
      this.view.contentDOM.removeEventListener("touchstart", this.touchStartHandler);
      this.view.contentDOM.removeEventListener("touchmove", this.touchMoveHandler);
      this.view.contentDOM.removeEventListener("touchend", this.touchEndHandler);
      this.view.contentDOM.removeEventListener("touchcancel", this.touchEndHandler);
      document.removeEventListener("pointermove", this.dragMoveHandler);
      document.removeEventListener("pointerup", this.dragEndHandler);
      document.removeEventListener("pointercancel", this.dragEndHandler);
    }
  }
);

// src/highlighter.ts
var import_view2 = require("@codemirror/view");
var import_state6 = require("@codemirror/state");
var blockHighlighter = import_view2.ViewPlugin.fromClass(
  class {
    constructor(view) {
      this.view = view;
      this.decorations = this.buildDecorations();
    }
    update(update) {
      const state = update.state.field(blockSelectionState);
      const prevState = update.startState.field(blockSelectionState);
      if (state.active !== prevState.active || state.selectedBlocks !== prevState.selectedBlocks || update.docChanged || update.viewportChanged) {
        this.decorations = this.buildDecorations();
      }
    }
    buildDecorations() {
      const state = this.view.state.field(blockSelectionState);
      if (!state.active || state.selectedBlocks.size === 0) {
        return import_view2.Decoration.none;
      }
      const builder = new import_state6.RangeSetBuilder();
      const lineDeco = import_view2.Decoration.line({ class: "block-editor-selected-line" });
      const sorted = Array.from(state.selectedBlocks).sort((a, b) => a - b);
      const doc = this.view.state.doc;
      for (const lineNum of sorted) {
        if (lineNum >= 1 && lineNum <= doc.lines) {
          const line = doc.line(lineNum);
          builder.add(line.from, line.from, lineDeco);
        }
      }
      return builder.finish();
    }
  },
  {
    decorations: (v) => v.decorations
  }
);

// src/toolbar.ts
var import_obsidian = require("obsidian");
var BlockEditorToolbar = class {
  constructor(indentUnit) {
    this.view = null;
    this.showingFormat = false;
    this.indentUnit = indentUnit;
    this.el = document.createElement("div");
    this.el.className = "block-editor-toolbar";
    this.el.style.display = "none";
    this.primaryDrawer = this.buildPrimaryDrawer();
    this.formatDrawer = this.buildFormatDrawer();
    this.el.appendChild(this.primaryDrawer);
    this.el.appendChild(this.formatDrawer);
  }
  setView(view) {
    this.view = view;
  }
  setIndentUnit(unit) {
    this.indentUnit = unit;
  }
  makeCloseButton(action) {
    const btn = document.createElement("button");
    btn.className = "block-editor-drawer-close";
    btn.setAttribute("aria-label", "Close");
    (0, import_obsidian.setIcon)(btn, "x");
    btn.addEventListener("pointerdown", (e) => {
      e.preventDefault();
      e.stopPropagation();
    });
    btn.addEventListener("pointerup", (e) => {
      e.preventDefault();
      e.stopPropagation();
      action();
    });
    return btn;
  }
  makeSeparator() {
    const sep = document.createElement("div");
    sep.className = "block-editor-pill-separator";
    return sep;
  }
  buildPrimaryDrawer() {
    const drawer = document.createElement("div");
    drawer.className = "block-editor-drawer block-editor-primary-drawer";
    drawer.style.display = "none";
    drawer.appendChild(this.makeCloseButton(() => this.exitBlockMode()));
    drawer.addEventListener("pointerdown", (e) => {
      if (e.target.closest("button"))
        return;
      e.preventDefault();
    });
    const row1 = document.createElement("div");
    row1.className = "block-editor-drawer-row";
    const movePill = document.createElement("div");
    movePill.className = "block-editor-format-pill block-editor-format-pill-stretch";
    movePill.appendChild(this.makeButton("case-sensitive", "Format", () => this.openFormatDrawer()));
    movePill.appendChild(this.makeSeparator());
    movePill.appendChild(this.makeButton("arrow-up", "Move Up", () => this.doAction(moveBlocksUp)));
    movePill.appendChild(this.makeButton("arrow-down", "Move Down", () => this.doAction(moveBlocksDown)));
    row1.appendChild(movePill);
    const insertPill = document.createElement("div");
    insertPill.className = "block-editor-format-pill block-editor-format-pill-stretch";
    insertPill.appendChild(this.makeButton("arrow-up-to-line", "Insert Above", () => this.doInsertAbove()));
    insertPill.appendChild(this.makeButton("arrow-down-to-line", "Insert Below", () => this.doInsertBelow()));
    insertPill.appendChild(this.makeButton("pencil", "Edit", () => this.doEditBlock()));
    row1.appendChild(insertPill);
    drawer.appendChild(row1);
    const row2 = document.createElement("div");
    row2.className = "block-editor-drawer-row";
    const clipPill = document.createElement("div");
    clipPill.className = "block-editor-format-pill block-editor-format-pill-stretch";
    clipPill.appendChild(this.makeButton("check-check", "Select All", () => this.doSelectAll()));
    clipPill.appendChild(this.makeButton("scissors", "Cut", () => this.doCut()));
    clipPill.appendChild(this.makeButton("copy", "Copy", () => this.doCopy()));
    row2.appendChild(clipPill);
    const undoPill = document.createElement("div");
    undoPill.className = "block-editor-format-pill block-editor-format-pill-stretch";
    undoPill.appendChild(this.makeButton("undo-2", "Undo", () => this.doUndo()));
    undoPill.appendChild(this.makeButton("redo-2", "Redo", () => this.doRedo()));
    undoPill.appendChild(this.makeSeparator());
    undoPill.appendChild(this.makeButton("trash-2", "Delete", () => this.doDelete(), "block-editor-btn-danger"));
    row2.appendChild(undoPill);
    drawer.appendChild(row2);
    return drawer;
  }
  buildFormatDrawer() {
    const drawer = document.createElement("div");
    drawer.className = "block-editor-drawer block-editor-format-drawer";
    drawer.style.display = "none";
    drawer.appendChild(this.makeCloseButton(() => this.closeFormatDrawer()));
    drawer.addEventListener("pointerdown", (e) => {
      if (e.target.closest("button"))
        return;
      e.preventDefault();
    });
    const label = document.createElement("div");
    label.className = "block-editor-format-label";
    label.textContent = "Format";
    drawer.appendChild(label);
    const headingRow = document.createElement("div");
    headingRow.className = "block-editor-format-headings";
    const headings = [
      { label: "Title (H1)", level: 1 },
      { label: "Subtitle (H2)", level: 2 },
      { label: "Heading (H3)", level: 3 },
      { label: "Strong (H4)", level: 4 },
      { label: "Body", level: 0 }
    ];
    for (const h of headings) {
      const btn = document.createElement("button");
      btn.className = `block-editor-heading-btn block-editor-heading-${h.level}`;
      btn.textContent = h.label;
      let downPos = null;
      btn.addEventListener("pointerdown", (e) => {
        e.preventDefault();
        e.stopPropagation();
        downPos = { x: e.clientX, y: e.clientY };
      });
      btn.addEventListener("pointerup", (e) => {
        if (!downPos)
          return;
        const dx = e.clientX - downPos.x;
        const dy = e.clientY - downPos.y;
        downPos = null;
        if (Math.sqrt(dx * dx + dy * dy) > 10)
          return;
        e.preventDefault();
        e.stopPropagation();
        const selected = this.getSelectedLines();
        if (selected && this.view) {
          setHeadingLevel(this.view, selected, h.level);
        }
      });
      btn.addEventListener("pointercancel", () => {
        downPos = null;
      });
      headingRow.appendChild(btn);
    }
    drawer.appendChild(headingRow);
    const listRow = document.createElement("div");
    listRow.className = "block-editor-format-row";
    const listPill = document.createElement("div");
    listPill.className = "block-editor-format-pill block-editor-format-pill-stretch";
    listPill.appendChild(this.makeButton("list", "Bullet List", () => this.doAction(toggleBulletList)));
    listPill.appendChild(this.makeButton("list-ordered", "Numbered List", () => this.doAction(toggleNumberedList)));
    listPill.appendChild(this.makeButton("check-square", "Checklist", () => this.doAction(toggleCheckbox)));
    listPill.appendChild(this.makeButton("text-quote", "Quote", () => this.doAction(toggleQuote)));
    listPill.appendChild(this.makeButton("code", "Code", () => this.doCodeFormat()));
    listRow.appendChild(listPill);
    drawer.appendChild(listRow);
    const inlineRow = document.createElement("div");
    inlineRow.className = "block-editor-format-row";
    const inlinePill = document.createElement("div");
    inlinePill.className = "block-editor-format-pill block-editor-format-pill-left";
    inlinePill.appendChild(this.makeButton("bold", "Bold", () => this.doInlineFormat("**")));
    inlinePill.appendChild(this.makeButton("italic", "Italic", () => this.doInlineFormat("*")));
    inlinePill.appendChild(this.makeButton("strikethrough", "Strikethrough", () => this.doInlineFormat("~~")));
    inlinePill.appendChild(this.makeButton("highlighter", "Highlight", () => this.doInlineFormat("==")));
    inlineRow.appendChild(inlinePill);
    const indentPill = document.createElement("div");
    indentPill.className = "block-editor-format-pill block-editor-format-pill-right";
    indentPill.appendChild(this.makeButton("outdent", "Outdent", () => this.doOutdent()));
    indentPill.appendChild(this.makeButton("indent", "Indent", () => this.doIndent()));
    inlineRow.appendChild(indentPill);
    drawer.appendChild(inlineRow);
    return drawer;
  }
  makeButton(icon, title, action, className) {
    const btn = document.createElement("button");
    btn.setAttribute("aria-label", title);
    btn.title = title;
    if (className)
      btn.classList.add(className);
    (0, import_obsidian.setIcon)(btn, icon);
    let downPos = null;
    btn.addEventListener("pointerdown", (e) => {
      e.preventDefault();
      e.stopPropagation();
      downPos = { x: e.clientX, y: e.clientY };
    });
    btn.addEventListener("pointerup", (e) => {
      if (!downPos)
        return;
      const dx = e.clientX - downPos.x;
      const dy = e.clientY - downPos.y;
      downPos = null;
      if (Math.sqrt(dx * dx + dy * dy) > 10)
        return;
      e.preventDefault();
      e.stopPropagation();
      action();
    });
    btn.addEventListener("pointercancel", () => {
      downPos = null;
    });
    return btn;
  }
  // ── Drawer open/close ──────────────────────────────────────────────────
  openFormatDrawer() {
    this.showingFormat = true;
    this.primaryDrawer.style.display = "none";
    this.formatDrawer.style.display = "flex";
  }
  closeFormatDrawer() {
    this.showingFormat = false;
    this.formatDrawer.style.display = "none";
    this.primaryDrawer.style.display = "flex";
  }
  exitBlockMode() {
    if (!this.view)
      return;
    this.view.dispatch({ effects: [toggleBlockMode.of(false)] });
  }
  // ── Visibility ─────────────────────────────────────────────────────────
  show() {
    this.el.style.display = "flex";
    if (this.showingFormat) {
      this.primaryDrawer.style.display = "none";
      this.formatDrawer.style.display = "flex";
    } else {
      this.primaryDrawer.style.display = "flex";
      this.formatDrawer.style.display = "none";
    }
  }
  hide() {
    this.el.style.display = "none";
    this.showingFormat = false;
  }
  destroy() {
    this.el.remove();
  }
  updateVisibility(active, hasSelection) {
    if (active && hasSelection) {
      this.show();
    } else {
      this.hide();
    }
  }
  // ── Action helpers ─────────────────────────────────────────────────────
  getSelectedLines() {
    if (!this.view)
      return null;
    const state = this.view.state.field(blockSelectionState);
    if (!state.active || state.selectedBlocks.size === 0)
      return null;
    return state.selectedBlocks;
  }
  doAction(fn) {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    fn(this.view, selected);
  }
  doIndent() {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    indentBlocks(this.view, selected, this.indentUnit);
  }
  doOutdent() {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    outdentBlocks(this.view, selected, this.indentUnit);
  }
  doDelete() {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    deleteBlocks(this.view, selected);
  }
  doCopy() {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    copyBlocks(this.view, selected);
  }
  doCut() {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    cutBlocks(this.view, selected);
  }
  doSelectAll() {
    if (!this.view)
      return;
    const state = this.view.state.field(blockSelectionState);
    progressiveSelectAll(this.view, state.selectedBlocks);
  }
  doInlineFormat(marker) {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    toggleInlineFormat(this.view, selected, marker);
  }
  doCodeFormat() {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    toggleCodeFormat(this.view, selected);
  }
  doUndo() {
    if (!this.view)
      return;
    undoAction(this.view);
  }
  doRedo() {
    if (!this.view)
      return;
    redoAction(this.view);
  }
  doInsertAbove() {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    insertAbove(this.view, selected);
  }
  doInsertBelow() {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    insertBelow(this.view, selected);
  }
  doEditBlock() {
    const selected = this.getSelectedLines();
    if (!selected || !this.view)
      return;
    editBlock(this.view, selected);
  }
};

// src/styles.ts
function injectStyles() {
  const style = document.createElement("style");
  style.id = "block-editor-styles";
  style.textContent = `
/* Gutter: invisible wrapper on document.body */
.block-editor-gutter {
	position: fixed;
	top: 0;
	left: 0;
	width: 0;
	height: 0;
	z-index: 5;
	pointer-events: none;
}

/* Each circle is position:fixed with its own top/left.
   The element is wider than the visual circle for a bigger tap target. */
.block-editor-gutter-circle {
	position: fixed;
	width: 44px;
	height: 28px;
	cursor: pointer;
	pointer-events: auto;
	z-index: 5;
	background: transparent;
	border: none;
	box-sizing: border-box;
	display: flex;
	align-items: center;
	justify-content: flex-start;
}

.block-editor-gutter-circle::before {
	content: "";
	width: 20px;
	height: 20px;
	border-radius: 50%;
	border: 2px solid var(--interactive-accent);
	background: var(--background-primary);
	transition: background-color 0.15s ease, transform 0.1s ease;
	box-sizing: border-box;
	flex-shrink: 0;
}

.block-editor-gutter-circle:active::before {
	transform: scale(0.9);
}

.block-editor-gutter-circle.selected::before {
	background: var(--interactive-accent);
}

/* Line highlight decoration \u2014 uses the native text selection color */
.cm-line.block-editor-selected-line {
	background-color: var(--text-selection) !important;
}

/* Toolbar container \u2014 full-width fixed at screen bottom */
.block-editor-toolbar {
	position: fixed;
	bottom: 0;
	left: 0;
	right: 0;
	display: flex;
	flex-direction: column;
	align-items: center;
	z-index: 100;
	pointer-events: none;
}

/* Hide Obsidian's native bottom toolbar when block editor toolbar is visible */
body.block-editor-active .workspace-drawer.mod-left,
body.block-editor-active .mobile-toolbar,
body.block-editor-active .workspace-tab-header-container {
	display: none !important;
}

/* \u2500\u2500 Drawer base \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 */
.block-editor-drawer {
	width: 100%;
	max-width: 500px;
	background: var(--background-secondary);
	border-radius: 38px 38px 0 0;
	border: none;
	padding: 16px 16px calc(16px + env(safe-area-inset-bottom, 0px));
	padding-top: 64px;
	display: flex;
	flex-direction: column;
	gap: 10px;
	pointer-events: auto;
	color: var(--text-normal);
	box-sizing: border-box;
	position: relative;
}

/* Close button \u2014 top right of drawer */
.block-editor-drawer-close {
	position: absolute;
	top: 16px;
	right: 16px;
	z-index: 1;
	min-width: 36px !important;
	height: 36px !important;
	border-radius: 50% !important;
}

.block-editor-drawer-close .svg-icon {
	width: 20px !important;
	height: 20px !important;
}

/* Row of buttons within a drawer */
.block-editor-drawer-row {
	display: flex;
	gap: 6px;
	align-items: center;
	width: 100%;
}

/* Vertical separator inside a pill */
.block-editor-pill-separator {
	width: 1px;
	height: 24px;
	background: var(--text-faint);
	opacity: 0.4;
	flex-shrink: 0;
}

/* Format label \u2014 positioned absolutely to match close button alignment */
.block-editor-format-label {
	position: absolute;
	top: 22px;
	left: 28px;
	font-size: 20px;
	font-weight: 700;
	color: var(--text-normal);
}

/* \u2500\u2500 All toolbar buttons \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 */
.block-editor-toolbar button {
	display: flex;
	align-items: center;
	justify-content: center;
	min-width: 40px;
	height: 40px;
	border: none !important;
	outline: none !important;
	border-radius: 10px;
	background: transparent !important;
	box-shadow: none !important;
	color: var(--text-normal);
	cursor: pointer;
	padding: 0;
	touch-action: manipulation;
	flex-shrink: 0;
	-webkit-appearance: none;
	appearance: none;
}

.block-editor-toolbar button:active {
	background: var(--background-modifier-hover) !important;
}

.block-editor-toolbar button.block-editor-btn-danger {
	color: var(--text-error);
}

.block-editor-toolbar button.block-editor-btn-danger:active {
	background: rgba(255, 59, 48, 0.12) !important;
}

/* Default icon size (format drawer) */
.block-editor-toolbar button .svg-icon {
	width: 20px;
	height: 20px;
	color: inherit;
	stroke: currentColor;
}

/* Larger icons in the primary drawer \u2014 must come after default rule */
.block-editor-primary-drawer button .svg-icon {
	width: 26px;
	height: 26px;
}

/* Primary drawer standalone buttons fill their row slot */
.block-editor-primary-drawer .block-editor-drawer-row > button {
	flex: 1;
	min-width: 0;
}

/* \u2500\u2500 Inner pills (used in both drawers) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 */
.block-editor-format-pill {
	display: flex;
	align-items: center;
	gap: 2px;
	padding: 2px;
	border-radius: 100px;
	background: var(--background-secondary-alt, var(--background-modifier-hover));
	border: none;
	position: relative;
}

.block-editor-format-pill button {
	min-width: 40px;
	height: 40px;
	border-radius: 100px !important;
}

/* Row 3 pill sizing: left pill (4 buttons) = flex 2, right pill (2 buttons) = flex 1 */
.block-editor-format-pill-left {
	flex: 2;
}

.block-editor-format-pill-left button {
	flex: 1;
	min-width: 0;
}

.block-editor-format-pill-right {
	flex: 1;
}

.block-editor-format-pill-right button {
	flex: 1;
	min-width: 0;
}

/* Stretch pill fills its full row */
.block-editor-format-pill-stretch {
	flex: 1;
}

.block-editor-format-pill-stretch button {
	flex: 1;
	min-width: 0;
}

.block-editor-format-pill button .svg-icon {
	width: 20px;
	height: 20px;
}

/* \u2500\u2500 Heading row (format drawer) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 */
.block-editor-format-headings {
	display: flex;
	gap: 0;
	overflow-x: auto;
	-webkit-overflow-scrolling: touch;
	scrollbar-width: none;
	padding: 0 4px;
}

.block-editor-format-headings::-webkit-scrollbar {
	display: none;
}

.block-editor-heading-btn {
	display: flex;
	align-items: center;
	justify-content: flex-start;
	border: none !important;
	outline: none !important;
	background: transparent !important;
	box-shadow: none !important;
	cursor: pointer;
	padding: 8px 12px !important;
	border-radius: 8px !important;
	color: var(--text-normal);
	white-space: nowrap;
	touch-action: manipulation;
	flex-shrink: 0;
	font-family: var(--font-text);
	height: auto !important;
	min-height: 40px;
	-webkit-appearance: none;
	appearance: none;
}

.block-editor-heading-btn:active {
	background: var(--background-modifier-hover) !important;
}

.block-editor-heading-1 {
	font-size: 24px;
	font-weight: 700;
}

.block-editor-heading-2 {
	font-size: 19px;
	font-weight: 700;
}

.block-editor-heading-3 {
	font-size: 16px;
	font-weight: 600;
}

.block-editor-heading-4 {
	font-size: 14px;
	font-weight: 700;
}

.block-editor-heading-0 {
	font-size: 14px;
	font-weight: 400;
	color: var(--text-muted);
}

/* \u2500\u2500 Format rows (format drawer) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 */
.block-editor-format-row {
	display: flex;
	gap: 6px;
	align-items: center;
	width: 100%;
}
`;
  document.head.appendChild(style);
  return style;
}
function removeStyles() {
  const el = document.getElementById("block-editor-styles");
  if (el)
    el.remove();
}

// src/main.ts
var BlockEditorPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.toolbar = null;
    this.styleEl = null;
  }
  async onload() {
    var _a, _b, _c, _d, _e, _f;
    this.styleEl = injectStyles();
    const useTab = (_c = (_b = (_a = this.app.vault).getConfig) == null ? void 0 : _b.call(_a, "useTab")) != null ? _c : true;
    const tabSize = (_f = (_e = (_d = this.app.vault).getConfig) == null ? void 0 : _e.call(_d, "tabSize")) != null ? _f : 4;
    const indentUnit = useTab ? "	" : " ".repeat(tabSize);
    this.toolbar = new BlockEditorToolbar(indentUnit);
    document.body.appendChild(this.toolbar.el);
    const toolbar = this.toolbar;
    const connectorPlugin = import_view3.ViewPlugin.fromClass(
      class {
        constructor(view) {
          this.view = view;
          toolbar.setView(view);
          this.syncState();
        }
        update(update) {
          toolbar.setView(this.view);
          this.syncState();
        }
        syncState() {
          const state = this.view.state.field(blockSelectionState);
          const hasSelection = state.selectedBlocks.size > 0;
          toolbar.updateVisibility(state.active, hasSelection);
          if (state.active) {
            document.body.classList.add("block-editor-active");
          } else {
            document.body.classList.remove("block-editor-active");
          }
          if (state.active && !hasSelection && !isDragSelecting()) {
            setTimeout(() => {
              const current = this.view.state.field(blockSelectionState);
              if (current.active && current.selectedBlocks.size === 0 && !isDragSelecting()) {
                setExitCooldown(this.view, Date.now() + 300);
                this.view.dispatch({
                  effects: [toggleBlockMode.of(false)]
                });
              }
            }, 0);
          }
        }
        destroy() {
          toolbar.hide();
          document.body.classList.remove("block-editor-active");
        }
      }
    );
    this.registerEditorExtension([
      blockSelectionState,
      blockModeTransactionFilter,
      blockSelectionGutter,
      blockHighlighter,
      connectorPlugin
    ]);
    const toggleBlock = (editor) => {
      const cmEditor = editor.cm;
      if (!cmEditor)
        return;
      const state = cmEditor.state.field(blockSelectionState);
      const newActive = !state.active;
      if (newActive) {
        const selected = /* @__PURE__ */ new Set();
        const hasFocus = cmEditor.hasFocus;
        if (hasFocus) {
          const sel = cmEditor.state.selection.main;
          const fromLine = cmEditor.state.doc.lineAt(sel.from).number;
          const toLine = cmEditor.state.doc.lineAt(sel.to).number;
          const visited = /* @__PURE__ */ new Set();
          for (let ln = fromLine; ln <= toLine; ln++) {
            if (visited.has(ln))
              continue;
            const [start, end] = getBlockWithChildren(cmEditor.state, ln, 4, true);
            for (let i = start; i <= end; i++) {
              visited.add(i);
              if (cmEditor.state.doc.line(i).text.trim() !== "") {
                selected.add(i);
              }
            }
          }
        } else {
          const doc = cmEditor.state.doc;
          let frontmatterEnd = 0;
          if (doc.lines >= 1 && doc.line(1).text.trim() === "---") {
            for (let i = 2; i <= doc.lines; i++) {
              if (doc.line(i).text.trim() === "---") {
                frontmatterEnd = i;
                break;
              }
            }
          }
          for (let ln = frontmatterEnd + 1; ln <= doc.lines; ln++) {
            if (doc.line(ln).text.trim() !== "") {
              const [start, end] = getBlockWithChildren(cmEditor.state, ln, 4, true);
              for (let i = start; i <= end; i++) {
                if (cmEditor.state.doc.line(i).text.trim() !== "") {
                  selected.add(i);
                }
              }
              break;
            }
          }
        }
        const effects = selected.size > 0 ? [toggleBlockMode.of(true), setBlockSelection.of(selected)] : [toggleBlockMode.of(true)];
        cmEditor.dispatch({ effects });
        cmEditor.contentDOM.blur();
      } else {
        cmEditor.dispatch({
          effects: [toggleBlockMode.of(false)]
        });
      }
    };
    this.addCommand({
      id: "toggle-block-mode",
      name: "Toggle Block Mode",
      icon: "layout-grid",
      editorCallback: toggleBlock
    });
    this.addRibbonIcon("layout-grid", "Toggle Block Mode", () => {
      const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
      if (markdownView) {
        toggleBlock(markdownView.editor);
      }
    });
  }
  onunload() {
    var _a;
    (_a = this.toolbar) == null ? void 0 : _a.destroy();
    document.body.classList.remove("block-editor-active");
    removeStyles();
  }
};
